import type { ConferenceProduct } from "./catalog";
import { TOA, brandImage, indicativeRange } from "./catalog.brands";

/**
 * TOA conference and discussion equipment.
 *
 * Only discussion-system hardware belongs here — TOA PA amplifiers and
 * loudspeakers stay on the PA System routes.
 */

const toaImage = (fileName: string) => brandImage("toa_products", fileName);

export const toaConferenceProducts: ConferenceProduct[] = [
  {
    id: "toa-ts-690-conference-system-central-unit",
    slug: "toa-ts-690-conference-system-central-unit",
    name: "TOA TS-690 Conference System Central Unit",
    model: "TS-690",
    brand: TOA,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["control-unit"],
    price: indicativeRange(55000, 85000, "plus"),
    availability: "project-order",
    shortDescription:
      "Central unit for the TOA TS-690 wired conference range, driving chairman and delegate stations from a single chassis.",
    images: [
      {
        src: toaImage("toa-ts-690-central-unit-for-wired-conference-system.webp"),
        alt: "TOA TS-690 central unit for wired conference system",
        primary: true,
      },
    ],
    compatibleProductIds: ["toa-ts-691l-conference-chairman-unit", "toa-ts-692l-conference-delegate-unit"],
    badge: "Central Unit",
    tags: ["TOA", "TS-690 Series", "Wired Conference"],
    keyFeatures: [
      "Powers and controls the full TS-690 discussion chain from one unit",
      "Selectable limit on how many microphones stay open together",
      "Recording and external amplifier outputs for minutes and hall audio",
      "Front-panel level control for adjustment without opening a rack",
    ],
    applications: ["Boardroom", "Government Meeting Room", "Training Centre"],
    specifications: [
      { key: "Model", value: "TS-690" },
      { key: "Series", value: "TOA TS-690 wired conference range" },
      { key: "Product Type", value: "Conference system central unit" },
      { key: "System Type", value: "Wired discussion" },
      { key: "Connection", value: "Wired chain to TS-691 and TS-692 stations" },
      { key: "Installation", value: "Rack or shelf mount at the AV position" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on station count and outputs" },
    ],
    description:
      "The TOA TS-690 is the central unit around which a TS-690 conference room is built. It supplies power to every chairman and delegate station on the chain, sets how many microphones may be open at once, and provides the recording and external amplifier outputs that a working meeting room needs. Level control on the front panel means an operator can correct the room mid-meeting without opening the rack. TOA's long presence in Bangladesh means spares and service knowledge are readily available, which matters for equipment expected to run for a decade. Sasha Corporation supports specification, BOQ preparation, installation, and after-sales service.",
  },
  {
    id: "toa-ts-691l-conference-chairman-unit",
    slug: "toa-ts-691l-conference-chairman-unit",
    name: "TOA TS-691L Conference Chairman Unit with Long Microphone",
    model: "TS-691L",
    brand: TOA,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["chairman-unit"],
    price: indicativeRange(27500, 29500),
    availability: "project-order",
    shortDescription:
      "Chairman station for TS-690 rooms with a long gooseneck, giving the chair priority over every open delegate microphone.",
    images: [
      {
        src: toaImage("toa-ts-691l-chairman-unit-with-long-microphone.webp"),
        alt: "TOA TS-691L conference chairman unit with long microphone",
        primary: true,
      },
    ],
    compatibleProductIds: ["toa-ts-690-conference-system-central-unit", "toa-ts-692l-conference-delegate-unit"],
    badge: "Chairman Unit",
    tags: ["TOA", "TS-690 Series", "Chairperson"],
    keyFeatures: [
      "Priority key mutes delegate microphones so the chair is heard at once",
      "Long gooseneck holds the capsule closer to the speaker on deep tables",
      "Speak indicator visible to participants across the room",
      "Shares cabling and power with the rest of the TS-690 chain",
    ],
    applications: ["Boardroom", "Council Chamber", "Committee Room"],
    specifications: [
      { key: "Model", value: "TS-691L" },
      { key: "Series", value: "TOA TS-690 wired conference range" },
      { key: "Product Type", value: "Chairman conference station" },
      { key: "Microphone", value: "Long gooseneck with speak indicator" },
      { key: "Chair Function", value: "Priority mute of active delegate microphones" },
      { key: "Installation", value: "Tabletop at the chairperson position" },
      { key: "Price Basis", value: "Indicative per-unit range; final quote depends on quantity" },
    ],
    description:
      "The TOA TS-691L takes the chairperson position in a TS-690 room. The priority key is what makes it a chairman unit rather than another delegate: pressing it mutes whatever delegate microphones are live, so the chair can bring a discussion back to order without waiting. The long gooseneck matters on deep boardroom tables where a short stem leaves the capsule too far from the speaker and pickup thins out. It runs on the same chain and power as the rest of the system. Sasha Corporation can confirm the correct gooseneck length against your table depth and supply, install, and support the full TS-690 room.",
  },
  {
    id: "toa-ts-692l-conference-delegate-unit",
    slug: "toa-ts-692l-conference-delegate-unit",
    name: "TOA TS-692L Conference Delegate Unit with Long Microphone",
    model: "TS-692L",
    brand: TOA,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["delegate-unit"],
    price: indicativeRange(22500, 27000),
    availability: "project-order",
    shortDescription:
      "Delegate station for TS-690 rooms with a long gooseneck, matched to the TS-691L chairman unit.",
    images: [
      {
        src: toaImage("toa-ts-692l-delegate-unit-with-long-microphone.webp"),
        alt: "TOA TS-692L conference delegate unit with long microphone",
        primary: true,
      },
    ],
    compatibleProductIds: ["toa-ts-690-conference-system-central-unit", "toa-ts-691l-conference-chairman-unit"],
    badge: "Delegate Unit",
    tags: ["TOA", "TS-690 Series", "Participant"],
    keyFeatures: [
      "Speak key with indicator ring showing the live state clearly",
      "Long gooseneck matched to the TS-691L for a consistent table",
      "Built-in loudspeaker mutes while the local microphone is open",
      "Chains along the table on the same cable as neighbouring stations",
    ],
    applications: ["Boardroom", "Committee Room", "Training Centre"],
    specifications: [
      { key: "Model", value: "TS-692L" },
      { key: "Series", value: "TOA TS-690 wired conference range" },
      { key: "Product Type", value: "Delegate conference station" },
      { key: "Microphone", value: "Long gooseneck with speak indicator" },
      { key: "Connection", value: "Wired chain to the TS-690 central unit" },
      { key: "Installation", value: "Tabletop at each participant position" },
      { key: "Price Basis", value: "Indicative per-unit range; final quote depends on quantity" },
    ],
    description:
      "The TOA TS-692L is the participant station in a TS-690 room, specified with the same long gooseneck as the TS-691L chairman unit so the table reads as one set rather than a collection of parts. Each station carries its own loudspeaker, muted while that microphone is open, which is what stops a room of live microphones turning into feedback. Delegate quantity is the number that decides most of a conference budget, so it is worth counting seats accurately rather than rounding up. Sasha Corporation can survey the table, confirm the count, and provide supply, installation, testing, and after-sales support in Bangladesh.",
  },
  {
    id: "toa-ts-682l-conference-delegate-unit",
    slug: "toa-ts-682l-conference-delegate-unit",
    name: "TOA TS-682L Conference Delegate Unit with Long Microphone",
    model: "TS-682L",
    brand: TOA,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["delegate-unit"],
    price: indicativeRange(18000, 25500),
    availability: "project-order",
    shortDescription:
      "Delegate station from the TOA TS-680 range with a long gooseneck, used where an installed TS-680 system is being extended.",
    images: [
      {
        src: toaImage("TOA-TS-682L-Delegate-Unit-with-Long-Microphone-300x300.webp"),
        alt: "TOA TS-682L delegate unit with long microphone",
        primary: true,
      },
    ],
    compatibleProductIds: [],
    badge: "Delegate Unit",
    tags: ["TOA", "TS-680 Series", "Participant"],
    keyFeatures: [
      "Extends or replaces positions on an existing TS-680 installation",
      "Long gooseneck for tables where the seat sits back from the edge",
      "Speak key and indicator consistent with the TS-680 range",
      "Wired chain operation with no batteries to maintain",
    ],
    applications: ["Boardroom", "Seminar Room", "Government Office"],
    specifications: [
      { key: "Model", value: "TS-682L" },
      { key: "Series", value: "TOA TS-680 wired conference range" },
      { key: "Product Type", value: "Delegate conference station" },
      { key: "Microphone", value: "Long gooseneck with speak indicator" },
      { key: "Connection", value: "Wired chain to a TS-680 series central unit" },
      { key: "Installation", value: "Tabletop at each participant position" },
      { key: "Price Basis", value: "Indicative per-unit range; final quote depends on quantity" },
    ],
    description:
      "The TOA TS-682L is a delegate station in the TS-680 range, and in practice most enquiries for it come from rooms that already have a TS-680 system running. Extending a working installation or replacing damaged positions is far cheaper than re-specifying a room, and TOA's continuity across the series is what makes that possible years after the original fit-out. The long gooseneck suits tables where participants sit back from the edge. Sasha Corporation can verify which TS-680 central unit you have installed before quoting, so the additional stations are known to be compatible, and can supply, fit, and support them.",
  },
  {
    id: "toa-ts-780-conference-system-central-unit",
    slug: "toa-ts-780-conference-system-central-unit",
    name: "TOA TS-780 Conference System Central Unit",
    model: "TS-780",
    brand: TOA,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["control-unit"],
    price: indicativeRange(126000, 172000),
    availability: "project-order",
    shortDescription:
      "Central unit for the TOA TS-780 conference range, sized for rooms that need more capacity than the TS-690 platform.",
    images: [
      {
        src: toaImage("toa-ts-780-bangladesh-toa-bangladesh-trimatrik.webp"),
        alt: "TOA TS-780 conference system central unit",
        primary: true,
      },
    ],
    compatibleProductIds: ["toa-ts-782-conference-delegate-unit"],
    badge: "Central Unit",
    tags: ["TOA", "TS-780 Series", "Wired Conference"],
    keyFeatures: [
      "Higher station capacity than the TS-690 central unit",
      "Discussion mode and open-microphone limit set centrally",
      "Recorder and external amplifier feeds for larger venues",
      "Rack-mount chassis suited to a permanent AV position",
    ],
    applications: ["Conference Hall", "University Auditorium", "Corporate Boardroom"],
    specifications: [
      { key: "Model", value: "TS-780" },
      { key: "Series", value: "TOA TS-780 conference range" },
      { key: "Product Type", value: "Conference system central unit" },
      { key: "System Type", value: "Wired discussion" },
      { key: "Connection", value: "Wired chain to TS-780 series stations" },
      { key: "Installation", value: "Rack mount at the AV position" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on station count and outputs" },
    ],
    description:
      "The TOA TS-780 central unit serves rooms that have outgrown the TS-690 platform. The step up is capacity rather than features — more stations on the chain, and the output provision to feed a hall reinforcement system rather than just a boardroom. For universities and conference venues in Bangladesh this is often the right first specification, because sizing a system to today's seating and finding it full in two years is a common and expensive mistake. Sasha Corporation can assess the realistic growth of your position count before recommending a platform, and provides BOQ preparation, installation, commissioning, and after-sales support.",
  },
  {
    id: "toa-ts-782-conference-delegate-unit",
    slug: "toa-ts-782-conference-delegate-unit",
    name: "TOA TS-782 Conference Delegate Unit",
    model: "TS-782",
    brand: TOA,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["delegate-unit"],
    price: indicativeRange(20500, 28500),
    availability: "project-order",
    shortDescription:
      "Delegate station for the TOA TS-780 range, the standard participant position on a TS-780 chain.",
    images: [
      { src: toaImage("toa-ts-782-delegate-unit.webp"), alt: "TOA TS-782 conference delegate unit", primary: true },
    ],
    compatibleProductIds: ["toa-ts-780-conference-system-central-unit"],
    badge: "Delegate Unit",
    tags: ["TOA", "TS-780 Series", "Participant"],
    keyFeatures: [
      "Standard participant station for TS-780 installations",
      "Speak key with clear live indication for the chair and the room",
      "Integrated loudspeaker muted during local microphone use",
      "Daisy-chain wiring that keeps table dressing simple",
    ],
    applications: ["Conference Hall", "Corporate Boardroom", "University Meeting Room"],
    specifications: [
      { key: "Model", value: "TS-782" },
      { key: "Series", value: "TOA TS-780 conference range" },
      { key: "Product Type", value: "Delegate conference station" },
      { key: "Microphone", value: "Gooseneck with speak indicator" },
      { key: "Connection", value: "Wired chain to the TS-780 central unit" },
      { key: "Installation", value: "Tabletop at each participant position" },
      { key: "Price Basis", value: "Indicative per-unit range; final quote depends on quantity" },
    ],
    description:
      "The TOA TS-782 is the everyday participant station on a TS-780 chain. Nothing about it is unusual, and that is the point — in a room with thirty positions, the delegate unit is the component that has to work identically thirty times without attention. Its speak indication is clear enough for the chair to read the state of the table at a glance, and the integrated loudspeaker mutes during local use to keep the room stable. Daisy-chain wiring keeps the cable dressing manageable under a long table. Sasha Corporation can confirm the position count, plan the cable runs, and provide supply, installation, and after-sales support in Bangladesh.",
  },
  {
    id: "toa-ts-791l-conference-chairman-unit",
    slug: "toa-ts-791l-conference-chairman-unit",
    name: "TOA TS-791L Conference Chairman Unit with Long Microphone",
    model: "TS-791L",
    brand: TOA,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["chairman-unit"],
    price: indicativeRange(26500, 36500),
    availability: "project-order",
    shortDescription:
      "Chairman station for the TOA TS-790 range with a long gooseneck and full priority control of the discussion floor.",
    images: [
      {
        src: toaImage("toa-ts-791l-chairman-unit-potential-of-your-conference-system.webp"),
        alt: "TOA TS-791L conference chairman unit with long microphone",
        primary: true,
      },
    ],
    compatibleProductIds: ["toa-ts-792l-conference-delegate-unit", "toa-ts-7912d-conference-central-unit"],
    badge: "Chairman Unit",
    tags: ["TOA", "TS-790 Series", "Chairperson"],
    keyFeatures: [
      "Priority control over every delegate microphone on the chain",
      "Long gooseneck for chairperson positions set back from the table edge",
      "Distinct key layout so priority is not pressed by mistake",
      "Matches the TS-792L delegate unit for a uniform head table",
    ],
    applications: ["Council Chamber", "Conference Hall", "Executive Boardroom"],
    specifications: [
      { key: "Model", value: "TS-791L" },
      { key: "Series", value: "TOA TS-790 conference range" },
      { key: "Product Type", value: "Chairman conference station" },
      { key: "Microphone", value: "Long gooseneck with speak indicator" },
      { key: "Chair Function", value: "Priority mute of all active delegate microphones" },
      { key: "Installation", value: "Tabletop at the chairperson position" },
      { key: "Price Basis", value: "Indicative per-unit range; final quote depends on quantity" },
    ],
    description:
      "The TOA TS-791L is the chairperson station in a TS-790 room. Its key layout deliberately separates the priority function from the ordinary speak key — a small design decision that saves a chair from silencing the room by accident during a long sitting. The long gooseneck suits head-table positions where the chair sits back from the edge with papers in front of them. Paired with TS-792L delegate units, the head table stays visually consistent. Sasha Corporation can plan the chairman and delegate arrangement around your seating protocol, and provides supply, installation, commissioning, and after-sales support across Bangladesh.",
  },
  {
    id: "toa-ts-792l-conference-delegate-unit",
    slug: "toa-ts-792l-conference-delegate-unit",
    name: "TOA TS-792L Conference Delegate Unit",
    model: "TS-792L",
    brand: TOA,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["delegate-unit"],
    price: indicativeRange(21500, 30000),
    availability: "project-order",
    shortDescription:
      "Delegate station for the TOA TS-790 range, matched to the TS-791L chairman unit.",
    images: [
      { src: toaImage("toa-ts-792l-delegate-unit.webp"), alt: "TOA TS-792L conference delegate unit", primary: true },
    ],
    compatibleProductIds: ["toa-ts-791l-conference-chairman-unit", "toa-ts-7912d-conference-central-unit"],
    badge: "Delegate Unit",
    tags: ["TOA", "TS-790 Series", "Participant"],
    keyFeatures: [
      "Participant station matched in housing to the TS-791L chairman unit",
      "Clear speak indication readable from the chair position",
      "Local loudspeaker muting to keep an open room stable",
      "Standard chain wiring for straightforward table extension",
    ],
    applications: ["Council Chamber", "Conference Hall", "Corporate Boardroom"],
    specifications: [
      { key: "Model", value: "TS-792L" },
      { key: "Series", value: "TOA TS-790 conference range" },
      { key: "Product Type", value: "Delegate conference station" },
      { key: "Microphone", value: "Gooseneck with speak indicator" },
      { key: "Connection", value: "Wired chain to a TS-790 series central unit" },
      { key: "Installation", value: "Tabletop at each participant position" },
      { key: "Price Basis", value: "Indicative per-unit range; final quote depends on quantity" },
    ],
    description:
      "The TOA TS-792L is the delegate station that partners the TS-791L chairman unit in a TS-790 room. Matching the housing across the head table and the body of the room is what makes a chamber look designed rather than assembled, and TOA keeps that consistency across the series. Functionally it does what a delegate station must: clear speak indication for the chair, local loudspeaker muting to hold the room stable, and chain wiring that lets positions be added later. Sasha Corporation can size the delegate count against your seating plan and provide supply, installation, testing, and after-sales support in Bangladesh.",
  },
  {
    id: "toa-ts-7912d-conference-central-unit",
    slug: "toa-ts-7912d-conference-central-unit",
    name: "TOA TS-7912D Conference System Central Unit",
    model: "TS-7912D",
    brand: TOA,
    systemTypes: ["audio", "digital"],
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["control-unit"],
    price: indicativeRange(148000, 205000),
    availability: "project-order",
    shortDescription:
      "Digital central unit for TS-790 rooms, handling discussion control and system power for larger chambers.",
    images: [
      {
        src: toaImage("toa-ts-7912d-central-unit-sound-system.webp"),
        alt: "TOA TS-7912D conference system central unit",
        primary: true,
      },
    ],
    compatibleProductIds: ["toa-ts-791l-conference-chairman-unit", "toa-ts-792l-conference-delegate-unit"],
    badge: "Central Unit",
    tags: ["TOA", "TS-790 Series", "Digital Control"],
    keyFeatures: [
      "Digital discussion control across the full TS-790 station chain",
      "Configurable open-microphone limits and discussion behaviour",
      "Outputs for recording and external hall reinforcement",
      "Rack chassis intended for a permanent control position",
    ],
    applications: ["Council Chamber", "Conference Hall", "Government Meeting Room"],
    specifications: [
      { key: "Model", value: "TS-7912D" },
      { key: "Series", value: "TOA TS-790 conference range" },
      { key: "Product Type", value: "Digital conference central unit" },
      { key: "System Type", value: "Wired digital discussion" },
      { key: "Connection", value: "Wired chain to TS-791 and TS-792 stations" },
      { key: "Installation", value: "Rack mount at the AV position" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on station count and interfaces" },
    ],
    description:
      "The TOA TS-7912D is the digital central unit for TS-790 installations. Compared with the analogue central units in TOA's older ranges, the practical gains are configurability and consistency: discussion behaviour is set rather than wired, and it stays identical from one sitting to the next. For council chambers and government meeting rooms where procedure is fixed and the same rules apply every session, that repeatability is worth more than flexibility. Recording and hall reinforcement outputs are provided as standard. Sasha Corporation can configure the discussion rules to match your standing orders, and handles installation, commissioning, and after-sales support.",
  },
  {
    id: "toa-ts-7912dw-conference-central-unit",
    slug: "toa-ts-7912dw-conference-central-unit",
    name: "TOA TS-7912DW Conference System Central Unit",
    model: "TS-7912DW",
    brand: TOA,
    systemTypes: ["audio", "digital"],
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["control-unit"],
    price: indicativeRange(162000, 224000),
    availability: "project-order",
    shortDescription:
      "Extended-capability TS-790 central unit for chambers that need more interface provision than the TS-7912D.",
    images: [
      {
        src: toaImage("toa-ts-7912dw-central-unit-powerhouse-for-wired-conference-systems.webp"),
        alt: "TOA TS-7912DW conference system central unit",
        primary: true,
      },
    ],
    compatibleProductIds: ["toa-ts-791l-conference-chairman-unit", "toa-ts-792l-conference-delegate-unit"],
    badge: "Central Unit",
    tags: ["TOA", "TS-790 Series", "Extended Capacity"],
    keyFeatures: [
      "Additional interface provision over the standard TS-7912D",
      "Suited to chambers integrating video, recording, and hall PA together",
      "Same discussion control model as the TS-7912D for operator familiarity",
      "Rack chassis for a permanent, serviced control position",
    ],
    applications: ["Assembly Hall", "Council Chamber", "Large Conference Venue"],
    specifications: [
      { key: "Model", value: "TS-7912DW" },
      { key: "Series", value: "TOA TS-790 conference range" },
      { key: "Product Type", value: "Digital conference central unit, extended interfaces" },
      { key: "System Type", value: "Wired digital discussion" },
      { key: "Integration", value: "Provision for recording, video, and hall reinforcement feeds" },
      { key: "Installation", value: "Rack mount at the AV or control room position" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on integration scope" },
    ],
    description:
      "The TOA TS-7912DW extends the TS-7912D with additional interface provision, and that is what decides between them. A boardroom that only needs discussion and a recording feed does not benefit from it; an assembly hall tying discussion audio into video capture, hall reinforcement, and an archive system does. The discussion control model is identical, so operators trained on one are trained on both. Choosing correctly here is mostly about being honest at design stage over what the room will actually be asked to do. Sasha Corporation can work through that with you, then deliver installation, commissioning, and long-term support in Bangladesh.",
  },
  {
    id: "toa-ts-820-conference-system-unit",
    slug: "toa-ts-820-conference-system-unit",
    name: "TOA TS-820 Conference System Unit",
    model: "TS-820",
    brand: TOA,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["control-unit"],
    price: indicativeRange(94000, 132000),
    availability: "project-order",
    shortDescription:
      "TOA TS-820 conference unit for compact wired discussion setups in small and medium meeting rooms.",
    images: [
      { src: toaImage("TOA-TS-820-Bangladesh-300x300.jpg.webp"), alt: "TOA TS-820 conference system unit", primary: true },
    ],
    compatibleProductIds: [],
    badge: "Central Unit",
    tags: ["TOA", "TS-800 Series", "Compact System"],
    keyFeatures: [
      "Compact wired conference platform for smaller room counts",
      "Simple commissioning without configuration software",
      "Serviceable in-country through TOA's established support network",
      "Cost-effective route into branded conference audio",
    ],
    applications: ["Small Meeting Room", "Departmental Boardroom", "Training Room"],
    specifications: [
      { key: "Model", value: "TS-820" },
      { key: "Series", value: "TOA TS-800 conference range" },
      { key: "Product Type", value: "Conference system unit" },
      { key: "System Type", value: "Wired discussion" },
      { key: "Room Scale", value: "Small to medium meeting rooms" },
      { key: "Installation", value: "Shelf or rack mount with wired station chain" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on station count" },
    ],
    description:
      "The TOA TS-820 covers compact wired conference setups where a full chamber platform would be over-specified. Commissioning does not involve configuration software, which keeps the installation short and means a facilities team can operate the room without training on a control interface. The practical argument for TOA at this level is service: the brand has been supported in Bangladesh long enough that spares and repair knowledge exist locally, which is not true of every budget conference system. Sasha Corporation can confirm the station count your room needs and provide supply, installation, testing, and after-sales support.",
  },
  {
    id: "toa-ts-910-conference-system-central-unit",
    slug: "toa-ts-910-conference-system-central-unit",
    name: "TOA TS-910 Conference System Central Unit",
    model: "TS-910",
    brand: TOA,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["control-unit"],
    price: indicativeRange(158000, 218000),
    availability: "project-order",
    shortDescription:
      "Central unit for the TOA TS-900 conference range, the platform TOA positions for large and formal chambers.",
    images: [
      { src: toaImage("TOA-TS-910-Bangladesh-300x300.jpg.webp"), alt: "TOA TS-910 conference system central unit", primary: true },
    ],
    compatibleProductIds: [
      "toa-ts-911-conference-chairman-unit",
      "toa-ts-912-conference-delegate-unit",
      "toa-ts-918-conference-expansion-unit",
    ],
    badge: "Central Unit",
    tags: ["TOA", "TS-900 Series", "Large Chamber"],
    keyFeatures: [
      "Top TOA conference platform for large and formal meeting chambers",
      "Expandable through the TS-918 unit as the position count grows",
      "Discussion modes suited to formal procedure and speaker queues",
      "Comprehensive output provision for recording and hall reinforcement",
    ],
    applications: ["Assembly Hall", "Council Chamber", "National Conference Venue"],
    specifications: [
      { key: "Model", value: "TS-910" },
      { key: "Series", value: "TOA TS-900 conference range" },
      { key: "Product Type", value: "Conference system central unit" },
      { key: "System Type", value: "Wired discussion" },
      { key: "Expansion", value: "Supports the TS-918 expansion unit for additional positions" },
      { key: "Installation", value: "Rack mount in the AV or control room" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on position count and expansion" },
    ],
    description:
      "The TOA TS-910 is the central unit of the TS-900 range, which is where TOA puts its provision for large and formal chambers. Two things justify the step up from the TS-780 and TS-790 platforms: the discussion modes suit formal procedure with speaker queues rather than open conversation, and the TS-918 expansion unit gives a defined route to grow the position count without replacing the core. For assembly halls and national venues where the room's life is measured in decades, that expansion path is the deciding factor. Sasha Corporation can plan the system with realistic growth headroom and deliver installation, commissioning, and long-term support.",
  },
  {
    id: "toa-ts-911-conference-chairman-unit",
    slug: "toa-ts-911-conference-chairman-unit",
    name: "TOA TS-911 Conference Chairman Unit",
    model: "TS-911",
    brand: TOA,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["chairman-unit"],
    price: indicativeRange(28500, 39500),
    availability: "project-order",
    shortDescription:
      "Chairman station for the TOA TS-900 range, built for chambers where the chair manages a formal speaker queue.",
    images: [
      {
        src: toaImage("TOA-TS-911-Bangladesh-Chairman-Unit-300x300.jpg.webp"),
        alt: "TOA TS-911 conference chairman unit",
        primary: true,
      },
    ],
    compatibleProductIds: ["toa-ts-910-conference-system-central-unit", "toa-ts-912-conference-delegate-unit"],
    badge: "Chairman Unit",
    tags: ["TOA", "TS-900 Series", "Formal Procedure"],
    keyFeatures: [
      "Priority control designed around formal speaker-queue procedure",
      "Robust build for chambers in continuous institutional use",
      "Clear indication of queue and live states for the chair",
      "Matched to the TS-912 delegate station across the chamber",
    ],
    applications: ["Assembly Hall", "Council Chamber", "Parliamentary Committee Room"],
    specifications: [
      { key: "Model", value: "TS-911" },
      { key: "Series", value: "TOA TS-900 conference range" },
      { key: "Product Type", value: "Chairman conference station" },
      { key: "Chair Function", value: "Priority control with formal speaker-queue management" },
      { key: "Connection", value: "Wired chain to the TS-910 central unit" },
      { key: "Installation", value: "Tabletop at the chairperson position" },
      { key: "Price Basis", value: "Indicative per-unit range; final quote depends on quantity" },
    ],
    description:
      "The TOA TS-911 is the chairman station in a TS-900 chamber, and it is designed around formal procedure rather than open discussion. Where a boardroom chair mainly needs to interrupt, an assembly chair needs to see and manage a queue — who has requested the floor, in what order, and who currently holds it. The TS-911's indication is built for that. Its construction also reflects institutional use, where a unit is handled by different people every sitting for many years. Sasha Corporation can configure the queue behaviour to match your standing orders and provide supply, installation, and long-term service support in Bangladesh.",
  },
  {
    id: "toa-ts-912-conference-delegate-unit",
    slug: "toa-ts-912-conference-delegate-unit",
    name: "TOA TS-912 Conference Delegate Unit",
    model: "TS-912",
    brand: TOA,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["delegate-unit"],
    price: indicativeRange(23500, 32500),
    availability: "project-order",
    shortDescription:
      "Delegate station for the TOA TS-900 range, with request-to-speak indication for formal chamber procedure.",
    images: [
      { src: toaImage("TOA-TS-912-Bangladesh-300x300.jpg.webp"), alt: "TOA TS-912 conference delegate unit", primary: true },
    ],
    compatibleProductIds: ["toa-ts-910-conference-system-central-unit", "toa-ts-911-conference-chairman-unit"],
    badge: "Delegate Unit",
    tags: ["TOA", "TS-900 Series", "Request to Speak"],
    keyFeatures: [
      "Request-to-speak indication so members can join the queue without interrupting",
      "Institutional build quality for chambers in constant use",
      "Matched housing with the TS-911 chairman station",
      "Chain wiring extendable through the TS-918 expansion unit",
    ],
    applications: ["Assembly Hall", "Council Chamber", "Committee Room"],
    specifications: [
      { key: "Model", value: "TS-912" },
      { key: "Series", value: "TOA TS-900 conference range" },
      { key: "Product Type", value: "Delegate conference station" },
      { key: "Speak Control", value: "Request-to-speak with queue indication" },
      { key: "Connection", value: "Wired chain to the TS-910 central unit" },
      { key: "Installation", value: "Tabletop at each member position" },
      { key: "Price Basis", value: "Indicative per-unit range; final quote depends on quantity" },
    ],
    description:
      "The TOA TS-912 is the member station in a TS-900 chamber. Its defining feature is request-to-speak: a member presses to join the queue rather than to open a microphone, and the chair grants the floor. In a chamber of any size this is the difference between orderly proceedings and several people talking at once. Build quality is aimed at institutional service, where the same unit is used by different people at every sitting for many years. Sasha Corporation can size the member count including expansion headroom, and provides supply, installation, commissioning, and after-sales support across Bangladesh.",
  },
  {
    id: "toa-ts-918-conference-expansion-unit",
    slug: "toa-ts-918-conference-expansion-unit",
    name: "TOA TS-918 Conference System Expansion Unit",
    model: "TS-918",
    brand: TOA,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["control-unit", "accessory"],
    price: indicativeRange(68000, 96000),
    availability: "project-order",
    shortDescription:
      "Expansion unit that extends a TOA TS-910 installation beyond the position count the central unit alone supports.",
    images: [
      {
        src: toaImage("TOA-TS-918-Bangladesh-Expansion-Unit-300x300.jpg.webp"),
        alt: "TOA TS-918 conference system expansion unit",
        primary: true,
      },
    ],
    compatibleProductIds: ["toa-ts-910-conference-system-central-unit"],
    badge: "Expansion Unit",
    tags: ["TOA", "TS-900 Series", "System Expansion"],
    keyFeatures: [
      "Extends TS-910 capacity without replacing the central unit",
      "Keeps one operator position across the expanded chamber",
      "Planned expansion route rather than a parallel second system",
      "Protects the original investment as seating grows",
    ],
    applications: ["Assembly Hall", "Council Chamber", "Large Conference Venue"],
    specifications: [
      { key: "Model", value: "TS-918" },
      { key: "Series", value: "TOA TS-900 conference range" },
      { key: "Product Type", value: "Conference system expansion unit" },
      { key: "Function", value: "Extends station capacity of a TS-910 installation" },
      { key: "Connection", value: "Wired link to the TS-910 central unit and onward chain" },
      { key: "Installation", value: "Rack mount alongside the central unit" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on added positions" },
    ],
    description:
      "The TOA TS-918 is what makes the TS-900 platform a long-term choice rather than a fixed one. When a chamber adds seats, the expansion unit extends the station chain while keeping the whole system under a single operator position — not two systems running side by side, which is what happens when a platform has no expansion route and a second central unit is bolted on. Planning cable provision for this at first fit-out costs very little; retrofitting it after the room is finished costs a great deal. Sasha Corporation can build that headroom into the original design and supply the expansion when it is needed.",
  },
  {
    id: "toa-yr-780-conference-extension-cord-10m",
    slug: "toa-yr-780-conference-extension-cord-10m",
    name: "TOA YR-780 Conference Extension Cord 10m",
    model: "YR-780",
    brand: TOA,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["accessory"],
    price: indicativeRange(4500, 7500),
    availability: "project-order",
    shortDescription:
      "Factory extension cord for TOA TS-780 conference chains, used to bridge gaps between table sections.",
    images: [
      { src: toaImage("toa-yr-780-10m-extension-cord.webp"), alt: "TOA YR-780 conference extension cord 10m", primary: true },
    ],
    compatibleProductIds: ["toa-ts-780-conference-system-central-unit", "toa-ts-782-conference-delegate-unit"],
    badge: "Accessory",
    tags: ["TOA", "TS-780 Series", "Cabling"],
    keyFeatures: [
      "Factory-terminated cord matched to TS-780 station connectors",
      "Bridges the gap between separated table sections or rows",
      "Removes the reliability risk of site-made conference cabling",
      "Ten-metre length suited to runs from the rack to the first station",
    ],
    applications: ["Conference Hall", "Boardroom", "Training Centre"],
    specifications: [
      { key: "Model", value: "YR-780" },
      { key: "Series", value: "TOA TS-780 conference range" },
      { key: "Product Type", value: "Conference system extension cord" },
      { key: "Length", value: "10 metres" },
      { key: "Compatibility", value: "TOA TS-780 series central unit and stations" },
      { key: "Installation", value: "Between the central unit and stations, or between table sections" },
      { key: "Price Basis", value: "Indicative per-unit range; final quote depends on quantity" },
    ],
    description:
      "The TOA YR-780 is a factory-terminated ten-metre extension cord for TS-780 conference chains. It solves two ordinary problems: reaching from the equipment rack to the first station on the table, and bridging between table sections that are physically separated in a U-shape or split-row layout. It is worth using the factory cord rather than a site-made assembly — conference chains carry power, audio, and control on the same cable, and a marginal termination shows up as intermittent faults that are difficult to trace once the table is dressed. Sasha Corporation can specify the correct cord count during layout planning and supply them with the system.",
  },
  {
    id: "toa-yr-790-conference-extension-cord-10m",
    slug: "toa-yr-790-conference-extension-cord-10m",
    name: "TOA YR-790 Conference Extension Cord 10m",
    model: "YR-790",
    brand: TOA,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["accessory"],
    price: indicativeRange(5200, 8500),
    availability: "project-order",
    shortDescription:
      "Ten-metre factory extension cord for TOA TS-790 conference chains and long rack-to-table runs.",
    images: [
      { src: toaImage("toa-yr-790-10-extension-cord.webp"), alt: "TOA YR-790 conference extension cord 10m", primary: true },
    ],
    compatibleProductIds: ["toa-ts-7912d-conference-central-unit", "toa-ts-792l-conference-delegate-unit"],
    badge: "Accessory",
    tags: ["TOA", "TS-790 Series", "Cabling"],
    keyFeatures: [
      "Matched to TS-790 series connectors and chain requirements",
      "Ten-metre run for racks positioned away from the conference table",
      "Consistent cable specification across the whole discussion chain",
      "Avoids the fault risk of mixing site-made and factory cabling",
    ],
    applications: ["Council Chamber", "Conference Hall", "Corporate Boardroom"],
    specifications: [
      { key: "Model", value: "YR-790" },
      { key: "Series", value: "TOA TS-790 conference range" },
      { key: "Product Type", value: "Conference system extension cord" },
      { key: "Length", value: "10 metres" },
      { key: "Compatibility", value: "TOA TS-790 series central units and stations" },
      { key: "Installation", value: "Rack-to-table runs and inter-section links" },
      { key: "Price Basis", value: "Indicative per-unit range; final quote depends on quantity" },
    ],
    description:
      "The TOA YR-790 is the ten-metre extension cord for TS-790 conference chains. In most chambers the equipment rack is not next to the table — it is in a control room or a cupboard at the side — and this is the cord that covers that first run. Keeping the whole chain on factory cable of one specification matters more than it appears: mixed cabling is the most common cause of intermittent faults on discussion systems, and those faults are hardest to find after the table is dressed and the room is in service. Sasha Corporation includes the correct cord quantities in the BOQ at design stage.",
  },
  {
    id: "toa-yr-790-3-conference-extension-cord-3m",
    slug: "toa-yr-790-3-conference-extension-cord-3m",
    name: "TOA YR-790-3 Conference Extension Cord 3m",
    model: "YR-790-3",
    brand: TOA,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["accessory"],
    price: indicativeRange(2600, 4500),
    availability: "project-order",
    shortDescription:
      "Short three-metre TS-790 extension cord for station-to-station links along a conference table.",
    images: [
      { src: toaImage("yr-790-3-extension-cord.webp"), alt: "TOA YR-790-3 conference extension cord 3m", primary: true },
    ],
    compatibleProductIds: ["toa-ts-791l-conference-chairman-unit", "toa-ts-792l-conference-delegate-unit"],
    badge: "Accessory",
    tags: ["TOA", "TS-790 Series", "Short Link"],
    keyFeatures: [
      "Three-metre length matched to normal seat-to-seat spacing",
      "Keeps excess cable off the floor and out of cable trays",
      "Same factory termination as the longer YR-790 cord",
      "Ordered per link, so a table is cabled without surplus",
    ],
    applications: ["Boardroom", "Committee Room", "Council Chamber"],
    specifications: [
      { key: "Model", value: "YR-790-3" },
      { key: "Series", value: "TOA TS-790 conference range" },
      { key: "Product Type", value: "Conference system extension cord" },
      { key: "Length", value: "3 metres" },
      { key: "Compatibility", value: "TOA TS-790 series stations" },
      { key: "Installation", value: "Station-to-station links along the table" },
      { key: "Price Basis", value: "Indicative per-unit range; final quote depends on quantity" },
    ],
    description:
      "The TOA YR-790-3 is the short cord used between adjacent stations on a TS-790 table. Three metres matches normal seat-to-seat spacing, which is the point — using ten-metre cords for every link leaves seven metres of surplus per position coiled under the table, and on a twenty-seat chamber that becomes a genuine cable-management problem as well as a needless cost. Specifying the right length per link keeps the installation tidy and the BOQ honest. Sasha Corporation works out the cord schedule from the table drawing during design, so the correct mix of short and long cords arrives with the system.",
  },
];
