import type { ConferenceProduct } from "./catalog";

/**
 * Brand conference products photographed for the Sasha catalog.
 *
 * Images live in /public/images/conference_system_products/<brand>_products/.
 * Only genuine conference/discussion equipment belongs here — PA amplifiers and
 * loudspeakers stay on the PA System routes so the Conference category keeps its
 * search relevance.
 *
 * Pricing is an indicative BDT project range, not a verified list price. Final
 * figures depend on unit count, cabling, and installation scope.
 */

const CONFERENCE_BRAND_IMAGE_BASE = "/images/conference_system_products";

export function brandImage(folder: string, fileName: string): string {
  return `${CONFERENCE_BRAND_IMAGE_BASE}/${folder}/${encodeURIComponent(fileName)}`;
}

const boschImage = (fileName: string) => brandImage("bosch_products", fileName);
const cmxImage = (fileName: string) => brandImage("cmx_products", fileName);

export const BOSCH = { name: "Bosch", slug: "bosch" } as const;
export const CMX = { name: "CMX", slug: "cmx" } as const;
export const TOA = { name: "TOA", slug: "toa" } as const;

export function indicativeRange(min: number, max: number): ConferenceProduct["price"] {
  const format = (value: number) => `৳${value.toLocaleString("en-US")}`;
  return {
    type: "range",
    min,
    max,
    currency: "BDT",
    displayLabel: `${format(min)} – ${format(max)}`,
  };
}

export const boschConferenceProducts: ConferenceProduct[] = [
  {
    id: "bosch-ccs-900-ultra-conference-system-unit",
    slug: "bosch-ccs-900-ultra-conference-system-unit",
    name: "Bosch CCS 900 Ultra Conference System Unit",
    model: "CCS 900 Ultra",
    brand: BOSCH,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["chairman-unit", "delegate-unit"],
    price: indicativeRange(26000, 39000),
    availability: "project-order",
    shortDescription:
      "Analogue discussion unit from the Bosch CCS 900 Ultra range, built for daisy-chained boardroom tables where setup speed matters more than configuration depth.",
    images: [
      {
        src: boschImage("Bosch-CCS-900-Ultra-Conference-System-Unit-300x300.webp"),
        alt: "Bosch CCS 900 Ultra Conference System discussion unit",
        primary: true,
      },
    ],
    compatibleProductIds: ["bosch-ccs-cu-conference-control-power-unit"],
    badge: "Discussion Unit",
    tags: ["Bosch", "CCS 900 Ultra", "Analogue Discussion"],
    keyFeatures: [
      "Discussion unit for the analogue CCS 900 Ultra family",
      "Loop-through cabling so units chain along the table without a patch panel",
      "Built-in loudspeaker mutes while the microphone is live to stop feedback",
      "Plug-and-play commissioning with no software configuration step",
    ],
    applications: ["Boardroom", "Council Chamber", "Training Room"],
    specifications: [
      { key: "Model", value: "CCS 900 Ultra" },
      { key: "Series", value: "Bosch CCS 900 Ultra discussion range" },
      { key: "Product Type", value: "Conference discussion unit" },
      { key: "System Type", value: "Analogue discussion" },
      { key: "Connection", value: "Wired, daisy-chain to the CCS-CU control unit" },
      { key: "Installation", value: "Tabletop, fixed or portable meeting layouts" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on unit count and cabling" },
    ],
    description:
      "The Bosch CCS 900 Ultra Conference System Unit covers the discussion position in Bosch's analogue meeting range. Units loop together along the table and run back to a single CCS-CU control unit, so a room can be cabled and commissioned without configuration software or a network switch. Each position carries its own loudspeaker, which mutes while that microphone is open to keep the room clear of feedback. It suits organisations in Bangladesh that want dependable Bosch build quality for boardrooms and council chambers without the overhead of a networked digital platform. Sasha Corporation can size the unit count, plan the cable runs, and handle installation and after-sales support.",
  },
  {
    id: "bosch-ccs-cu-conference-control-power-unit",
    slug: "bosch-ccs-cu-conference-control-power-unit",
    name: "Bosch CCS-CU Conference Control & Power Unit",
    model: "CCS-CU",
    brand: BOSCH,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["control-unit"],
    price: indicativeRange(118000, 165000),
    availability: "project-order",
    shortDescription:
      "Central control and power unit for CCS 900 Ultra rooms, driving the discussion loop and handling recording and PA output from one rack position.",
    images: [
      {
        src: boschImage("Bosch-CCS-CU-Conference-Control-Power-Unit-300x300.webp"),
        alt: "Bosch CCS-CU conference control and power unit",
        primary: true,
      },
    ],
    compatibleProductIds: ["bosch-ccs-900-ultra-conference-system-unit"],
    badge: "Central Unit",
    tags: ["Bosch", "CCS 900 Ultra", "Control Unit"],
    keyFeatures: [
      "Powers and controls the full CCS 900 Ultra discussion loop from one chassis",
      "Active-microphone limit selectable so only a set number of positions speak at once",
      "Recorder and external PA outputs for minute-taking and hall reinforcement",
      "Front-panel master volume and tone control for quick room adjustment",
    ],
    applications: ["Boardroom", "Council Chamber", "Government Meeting Room"],
    specifications: [
      { key: "Model", value: "CCS-CU" },
      { key: "Series", value: "Bosch CCS 900 Ultra discussion range" },
      { key: "Product Type", value: "Conference control and power unit" },
      { key: "System Type", value: "Analogue discussion" },
      { key: "Connection", value: "Wired trunk to daisy-chained discussion units" },
      { key: "Installation", value: "Rack or shelf mount at the AV position" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on room size and interface needs" },
    ],
    description:
      "The Bosch CCS-CU is the heart of a CCS 900 Ultra installation. It supplies power to every discussion unit on the loop, governs how many microphones may be open at the same time, and provides the recorder and external amplifier outputs a meeting room needs for minutes and larger-hall reinforcement. Master volume and tone sit on the front panel so an operator can correct the room without opening software. For Bangladeshi government offices, universities, and corporate boardrooms this keeps the entire discussion system under one serviceable device. Sasha Corporation supports specification, BOQ preparation, commissioning, and warranty service.",
  },
  {
    id: "bosch-ccsd-cu-ccs-1000-d-conference-control-unit",
    slug: "bosch-ccsd-cu-ccs-1000-d-conference-control-unit",
    name: "Bosch CCSD-CU CCS 1000 D Conference Control Unit",
    model: "CCSD-CU",
    brand: BOSCH,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["control-unit"],
    price: indicativeRange(185000, 245000),
    availability: "project-order",
    shortDescription:
      "Digital control unit for the CCS 1000 D platform, configured from a browser instead of front-panel menus.",
    images: [
      { src: boschImage("Bosch-CCSD-CU-300x300.webp"), alt: "Bosch CCSD-CU CCS 1000 D conference control unit", primary: true },
    ],
    compatibleProductIds: [
      "bosch-ccs-1000-d-chairman-unit",
      "bosch-ccs-1000-d-delegate-unit",
      "bosch-ccsd-curd-ccs-1000-d-control-unit-with-recording",
    ],
    badge: "Central Unit",
    tags: ["Bosch", "CCS 1000 D", "Digital Discussion"],
    keyFeatures: [
      "Digital discussion control with browser-based setup from a laptop or tablet",
      "Discussion modes including open, override, and request-to-speak queueing",
      "Single-cable daisy chain carries audio, data, and power to each device",
      "Camera-control trigger so the active speaker can be followed on video",
    ],
    applications: ["Boardroom", "Council Chamber", "University Senate Room"],
    specifications: [
      { key: "Model", value: "CCSD-CU" },
      { key: "Series", value: "Bosch CCS 1000 D digital discussion" },
      { key: "Product Type", value: "Digital conference control unit" },
      { key: "System Type", value: "Digital discussion" },
      { key: "Connection", value: "Wired daisy chain to CCS 1000 D discussion devices" },
      { key: "Configuration", value: "Web browser interface over the unit's own access point or LAN" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on device count and integration scope" },
    ],
    description:
      "The Bosch CCSD-CU brings the CCS 1000 D digital discussion platform into rooms that need more control than an analogue loop provides. Setup runs through a web browser, so discussion modes, speaker limits, and request-to-speak queues are adjusted from a laptop or tablet rather than a front panel. A single daisy-chain cable carries audio, control data, and power to each discussion device, which keeps table dressing simple even in rooms with many positions. Camera-control triggers let an integrated video system follow whoever is speaking. Sasha Corporation handles system design, configuration, installation, and ongoing support for CCS 1000 D projects across Bangladesh.",
  },
  {
    id: "bosch-ccsd-curd-ccs-1000-d-control-unit-with-recording",
    slug: "bosch-ccsd-curd-ccs-1000-d-control-unit-with-recording",
    name: "Bosch CCSD-CURD CCS 1000 D Control Unit with Recording",
    model: "CCSD-CURD",
    brand: BOSCH,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["control-unit"],
    price: indicativeRange(225000, 298000),
    availability: "project-order",
    shortDescription:
      "CCS 1000 D control unit with onboard meeting recording, aimed at rooms where a verbatim audio record is part of the procedure.",
    images: [
      {
        src: boschImage("Bosch-CCSD-CURD-300x300.webp"),
        alt: "Bosch CCSD-CURD CCS 1000 D control unit with recording",
        primary: true,
      },
    ],
    compatibleProductIds: ["bosch-ccs-1000-d-chairman-unit", "bosch-ccs-1000-d-delegate-unit"],
    badge: "Recording Unit",
    tags: ["Bosch", "CCS 1000 D", "Meeting Recording"],
    keyFeatures: [
      "Records proceedings to USB storage without an external recorder in the rack",
      "Same browser-based discussion control as the standard CCS 1000 D control unit",
      "Suited to statutory meetings where the audio record forms part of the minutes",
      "One device covers discussion control, power, and archiving together",
    ],
    applications: ["Council Chamber", "Government Meeting Room", "Corporate Boardroom"],
    specifications: [
      { key: "Model", value: "CCSD-CURD" },
      { key: "Series", value: "Bosch CCS 1000 D digital discussion" },
      { key: "Product Type", value: "Digital conference control unit with recording" },
      { key: "System Type", value: "Digital discussion" },
      { key: "Recording", value: "Onboard capture of meeting audio to USB storage" },
      { key: "Configuration", value: "Web browser interface for discussion modes and speaker limits" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on device count and storage policy" },
    ],
    description:
      "The Bosch CCSD-CURD is the recording variant of the CCS 1000 D control unit. Alongside the discussion control, power, and browser configuration of the standard model, it captures the meeting audio directly to USB storage, removing the separate recorder that minute-taking rooms would otherwise need. That matters for councils, regulatory bodies, and boards in Bangladesh where the audio record is part of the official procedure rather than a convenience. Because control and archiving live in one chassis, there is a single device to rack, power, and service. Sasha Corporation can advise on storage handling, configure discussion modes to your meeting rules, and provide installation and after-sales support.",
  },
  {
    id: "bosch-ccs-1000-d-chairman-unit",
    slug: "bosch-ccs-1000-d-chairman-unit",
    name: "Bosch CCS 1000 D Chairman Unit",
    model: "CCS 1000 D Chairman",
    brand: BOSCH,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["chairman-unit"],
    price: indicativeRange(32000, 46000),
    availability: "project-order",
    shortDescription:
      "Chairperson position for CCS 1000 D rooms, with a priority key that clears the floor when the chair needs to speak.",
    images: [
      {
        src: boschImage("ccs1000dchairman-in-Bangladesh-300x300.webp"),
        alt: "Bosch CCS 1000 D chairman discussion unit",
        primary: true,
      },
    ],
    compatibleProductIds: ["bosch-ccsd-cu-ccs-1000-d-conference-control-unit", "bosch-ccs-1000-d-delegate-unit"],
    badge: "Chairman Unit",
    tags: ["Bosch", "CCS 1000 D", "Chairperson"],
    keyFeatures: [
      "Priority key mutes open delegate microphones so the chair is heard immediately",
      "Same physical footprint as the delegate unit for a consistent table layout",
      "Directional gooseneck microphone with a clear speak indicator ring",
      "Single-cable daisy chain shared with the rest of the discussion loop",
    ],
    applications: ["Boardroom", "Council Chamber", "Committee Room"],
    specifications: [
      { key: "Model", value: "CCS 1000 D Chairman" },
      { key: "Series", value: "Bosch CCS 1000 D digital discussion" },
      { key: "Product Type", value: "Chairman discussion unit" },
      { key: "Chair Function", value: "Priority key to interrupt and clear active delegate microphones" },
      { key: "Microphone", value: "Pluggable gooseneck with speak indicator" },
      { key: "Installation", value: "Tabletop at the chairperson position" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on microphone length and quantity" },
    ],
    description:
      "The Bosch CCS 1000 D Chairman Unit occupies the chairperson seat in a digital discussion room. Its priority key mutes whatever delegate microphones are open, so the chair can take the floor without waiting for a queue to clear — the difference between a meeting that stays on schedule and one that does not. Physically it matches the delegate unit, keeping the table visually consistent, and it shares the same single-cable daisy chain. For committee rooms, councils, and boardrooms in Bangladesh it gives the chair practical control of the discussion. Sasha Corporation supplies matched chairman and delegate quantities, plans the table layout, and supports installation and service.",
  },
  {
    id: "bosch-ccs-1000-d-delegate-unit",
    slug: "bosch-ccs-1000-d-delegate-unit",
    name: "Bosch CCS 1000 D Delegate Unit",
    model: "CCS 1000 D Delegate",
    brand: BOSCH,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["delegate-unit"],
    price: indicativeRange(27000, 38000),
    availability: "project-order",
    shortDescription:
      "Participant position for CCS 1000 D rooms, with request-to-speak behaviour set centrally by the control unit.",
    images: [
      {
        src: boschImage("ccs1000d-delegate-in-Bangladesh-Bosch-300x300.webp"),
        alt: "Bosch CCS 1000 D delegate discussion unit",
        primary: true,
      },
    ],
    compatibleProductIds: ["bosch-ccsd-cu-ccs-1000-d-conference-control-unit", "bosch-ccs-1000-d-chairman-unit"],
    badge: "Delegate Unit",
    tags: ["Bosch", "CCS 1000 D", "Participant"],
    keyFeatures: [
      "Speak key with indicator ring showing live and queued states",
      "Request-to-speak queueing when the control unit is set to that mode",
      "Integrated loudspeaker that mutes while the local microphone is open",
      "Scales across the table on the same daisy-chain cable as the chairman unit",
    ],
    applications: ["Boardroom", "Committee Room", "Training Room"],
    specifications: [
      { key: "Model", value: "CCS 1000 D Delegate" },
      { key: "Series", value: "Bosch CCS 1000 D digital discussion" },
      { key: "Product Type", value: "Delegate discussion unit" },
      { key: "Speak Control", value: "Speak key with request-to-speak queue support" },
      { key: "Microphone", value: "Pluggable gooseneck with speak indicator" },
      { key: "Installation", value: "Tabletop at each participant position" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on quantity and microphone length" },
    ],
    description:
      "The Bosch CCS 1000 D Delegate Unit is the participant position in a digital discussion room. How it behaves depends on the mode set at the control unit: it can open the microphone immediately, hold the request in a queue, or override the oldest active speaker. That flexibility lets one set of hardware serve a relaxed project meeting and a formal committee sitting equally well. Each unit carries its own loudspeaker, muted while the local microphone is live so the room stays free of feedback. Sasha Corporation can calculate the delegate count for your table, prepare the BOQ, and provide installation, testing, and after-sales support in Bangladesh.",
  },
];

export const cmxConferenceProducts: ConferenceProduct[] = [
  {
    id: "cmx-5g-100mc-wifi-wireless-conference-controller",
    slug: "cmx-5g-100mc-wifi-wireless-conference-controller",
    name: "CMX 5G-100MC Wi-Fi Wireless Conference Controller",
    model: "5G-100MC",
    brand: CMX,
    systemCategory: "audio",
    connection: "wireless",
    productTypes: ["control-unit"],
    price: indicativeRange(165000, 225000),
    availability: "project-order",
    shortDescription:
      "Wi-Fi based conference master controller for rooms where running cable under the table is not an option.",
    images: [
      {
        src: cmxImage("CMX-5G-100MC-Wi-Fi-Wireless-Conference-Controller-300x300.webp"),
        alt: "CMX 5G-100MC Wi-Fi wireless conference controller",
        primary: true,
      },
    ],
    compatibleProductIds: ["cmx-5g-157-5g-158-wireless-discussion-units"],
    badge: "Wireless System",
    tags: ["CMX", "Wi-Fi Conference", "5G Series"],
    keyFeatures: [
      "Wireless link to discussion units over a dedicated Wi-Fi band",
      "No floor trunking or table cable channels required during fit-out",
      "Central control of speak limits and discussion mode from the host",
      "Suits heritage rooms and leased offices where drilling is restricted",
    ],
    applications: ["Executive Boardroom", "Hotel Conference Room", "Heritage Meeting Hall"],
    specifications: [
      { key: "Model", value: "5G-100MC" },
      { key: "Series", value: "CMX 5G wireless conference range" },
      { key: "Product Type", value: "Wireless conference master controller" },
      { key: "System Type", value: "Wi-Fi wireless discussion" },
      { key: "Connection", value: "Wireless to paired 5G-series discussion units" },
      { key: "Installation", value: "Rack or shelf mount with clear line of sight to the table" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on unit count and site survey" },
    ],
    description:
      "The CMX 5G-100MC is a Wi-Fi based conference master controller for rooms that cannot take cable. Heritage halls, leased offices, and rooms with stone or marble floors often make table trunking impractical or forbidden — this controller pairs discussion units over a dedicated wireless band instead, so a meeting room can be commissioned without civil work. Speak limits and discussion mode are still managed centrally from the host, so the chair keeps the same control a wired system would give. A site survey matters here more than with wired systems, and Sasha Corporation can carry that out, size the unit count, and support commissioning and service in Bangladesh.",
  },
  {
    id: "cmx-5g-157-5g-158-wireless-discussion-units",
    slug: "cmx-5g-157-5g-158-wireless-discussion-units",
    name: "CMX 5G-157 Chairman & 5G-158 Delegate Wireless Units",
    model: "5G-157 / 5G-158",
    brand: CMX,
    systemCategory: "audio",
    connection: "wireless",
    productTypes: ["chairman-unit", "delegate-unit"],
    price: indicativeRange(29000, 42000),
    availability: "project-order",
    shortDescription:
      "Matched wireless chairman and delegate pair for the CMX 5G platform, battery powered and free of any table cabling.",
    images: [
      {
        src: cmxImage("CMX-5G-157-Chairman-5G-158-Delegate-Units-300x300.webp"),
        alt: "CMX 5G-157 chairman and 5G-158 delegate wireless conference units",
        primary: true,
      },
    ],
    compatibleProductIds: ["cmx-5g-100mc-wifi-wireless-conference-controller"],
    badge: "Wireless Delegate",
    tags: ["CMX", "Wireless Discussion", "5G Series"],
    keyFeatures: [
      "Chairman and delegate variants share one charging and spares inventory",
      "Battery powered, so the table can be re-arranged between meetings",
      "Chairman priority mutes delegate microphones when the chair speaks",
      "Pairs to the 5G-100MC controller without per-unit configuration",
    ],
    applications: ["Executive Boardroom", "Hotel Conference Room", "Flexible Meeting Space"],
    specifications: [
      { key: "Models", value: "5G-157 chairman, 5G-158 delegate" },
      { key: "Series", value: "CMX 5G wireless conference range" },
      { key: "Product Type", value: "Wireless chairman and delegate discussion units" },
      { key: "Power", value: "Rechargeable battery operation" },
      { key: "Connection", value: "Wireless pairing to the 5G-100MC master controller" },
      { key: "Installation", value: "Tabletop, repositionable between meetings" },
      { key: "Price Basis", value: "Indicative per-unit range; final quote depends on chairman/delegate split" },
    ],
    description:
      "The CMX 5G-157 chairman and 5G-158 delegate units are the table positions for a CMX 5G wireless room. Because they run on rechargeable batteries and pair to the controller without cabling, the table can be reconfigured between a board meeting and a training session without an AV callout. The two variants share a chassis, so charging trays and spare parts cover both. The chairman unit adds the priority function that mutes delegate microphones when the chair takes the floor. Sasha Corporation can work out the chairman-to-delegate ratio for your room, plan charging logistics, and provide installation and after-sales support across Bangladesh.",
  },
  {
    id: "cmx-cs-100-s101-s102-digital-conference-system",
    slug: "cmx-cs-100-s101-s102-digital-conference-system",
    name: "CMX CS-100 with S101 & S102 Digital Conference System",
    model: "CS-100 / S101 / S102",
    brand: CMX,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["package", "control-unit", "chairman-unit", "delegate-unit"],
    price: indicativeRange(215000, 340000),
    availability: "project-order",
    shortDescription:
      "Entry digital discussion package pairing the CS-100 controller with S101 chairman and S102 delegate units.",
    images: [
      {
        src: cmxImage("CMX-CS-100-S101-S102-Digital-Conference-System-300x300.webp"),
        alt: "CMX CS-100 digital conference system with S101 chairman and S102 delegate units",
        primary: true,
      },
    ],
    compatibleProductIds: [],
    badge: "Complete Package",
    tags: ["CMX", "Digital Discussion", "Starter System"],
    keyFeatures: [
      "Controller, chairman, and delegate units specified as one matched package",
      "Removes the compatibility guesswork of assembling parts separately",
      "Sized for small and medium meeting rooms rather than large halls",
      "Straightforward wired chain that a local team can maintain",
    ],
    applications: ["Small Meeting Room", "Departmental Boardroom", "Training Room"],
    specifications: [
      { key: "Models", value: "CS-100 controller, S101 chairman, S102 delegate" },
      { key: "Series", value: "CMX CS digital conference range" },
      { key: "Product Type", value: "Complete digital discussion package" },
      { key: "System Type", value: "Wired digital discussion" },
      { key: "Room Scale", value: "Small to medium meeting rooms" },
      { key: "Installation", value: "Tabletop units with a wired chain to the controller" },
      { key: "Price Basis", value: "Indicative package range; final quote depends on the delegate count supplied" },
    ],
    description:
      "The CMX CS-100 package brings the controller, S101 chairman unit, and S102 delegate units together as one specified system. For a first conference room this removes the most common source of trouble — parts bought separately that turn out not to match. The scale is deliberately modest: this is a package for departmental boardrooms and training rooms, not a council chamber. The wired chain is simple enough that an in-house facilities team can look after day-to-day operation once it is commissioned. Sasha Corporation can confirm the delegate quantity against your table, prepare the BOQ, and handle installation, testing, and after-sales support in Bangladesh.",
  },
  {
    id: "cmx-cs-700a-conference-system-with-discussion-units",
    slug: "cmx-cs-700a-conference-system-with-discussion-units",
    name: "CMX CS-700A Conference System with Discussion Units",
    model: "CS-700A",
    brand: CMX,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["package", "control-unit"],
    price: indicativeRange(268000, 395000),
    availability: "project-order",
    shortDescription:
      "Mid-range CMX discussion system supplied with its matched table units for rooms that have outgrown an entry package.",
    images: [
      {
        src: cmxImage("CMX-CS-700A-Conference-System-with-Discussion-Units-768x768.webp"),
        alt: "CMX CS-700A conference system with discussion units",
        primary: true,
      },
    ],
    compatibleProductIds: ["cmx-cs-903-cs-904-chairman-delegate-units"],
    badge: "Complete Package",
    tags: ["CMX", "Discussion System", "CS Series"],
    keyFeatures: [
      "Headroom for more table positions than the entry CS-100 package",
      "Controller and discussion units supplied and tested as a set",
      "Discussion mode and speak limits managed from the controller",
      "Wired architecture that stays predictable as positions are added",
    ],
    applications: ["Corporate Boardroom", "University Meeting Hall", "Government Office"],
    specifications: [
      { key: "Model", value: "CS-700A" },
      { key: "Series", value: "CMX CS digital conference range" },
      { key: "Product Type", value: "Conference system with discussion units" },
      { key: "System Type", value: "Wired digital discussion" },
      { key: "Room Scale", value: "Medium to large meeting rooms" },
      { key: "Installation", value: "Rack-mounted controller with tabletop discussion units" },
      { key: "Price Basis", value: "Indicative package range; final quote depends on the number of positions" },
    ],
    description:
      "The CMX CS-700A sits a step above the entry CS packages, aimed at rooms where the position count has grown past what a starter system handles comfortably. It ships with matched discussion units, so the controller and table hardware are known-good together before they reach site. Discussion mode and the number of simultaneously open microphones stay under the controller's management, which is what keeps a larger table orderly. Because the architecture is wired, behaviour remains predictable as positions are added later. Sasha Corporation can assess your room, size the system honestly against the seating, and provide installation, commissioning, and after-sales support in Bangladesh.",
  },
  {
    id: "cmx-cs-903-cs-904-chairman-delegate-units",
    slug: "cmx-cs-903-cs-904-chairman-delegate-units",
    name: "CMX CS-903 Chairman & CS-904 Delegate Units",
    model: "CS-903 / CS-904",
    brand: CMX,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["chairman-unit", "delegate-unit"],
    price: indicativeRange(17500, 26000),
    availability: "project-order",
    shortDescription:
      "Wired chairman and delegate pair for CMX CS rooms, used to extend or replace positions on an existing table.",
    images: [
      {
        src: cmxImage("CMX-CS-903-Chairman-CS-904-Delegate-Units-300x300.webp"),
        alt: "CMX CS-903 chairman and CS-904 delegate conference units",
        primary: true,
      },
    ],
    compatibleProductIds: ["cmx-cs-700a-conference-system-with-discussion-units"],
    badge: "Chairman Unit",
    tags: ["CMX", "CS Series", "Table Unit"],
    keyFeatures: [
      "Add positions to an existing CS-series room without replacing the controller",
      "Chairman variant carries the priority function for floor control",
      "Consistent housing keeps a mixed-age table looking uniform",
      "Gooseneck microphone with a visible speak indicator",
    ],
    applications: ["Corporate Boardroom", "Committee Room", "Government Office"],
    specifications: [
      { key: "Models", value: "CS-903 chairman, CS-904 delegate" },
      { key: "Series", value: "CMX CS digital conference range" },
      { key: "Product Type", value: "Chairman and delegate discussion units" },
      { key: "Chair Function", value: "Priority mute of active delegate microphones" },
      { key: "Connection", value: "Wired chain to a CMX CS controller" },
      { key: "Installation", value: "Tabletop at chairman and participant positions" },
      { key: "Price Basis", value: "Indicative per-unit range; final quote depends on quantity and split" },
    ],
    description:
      "The CMX CS-903 chairman and CS-904 delegate units are the table positions for CMX CS-series rooms. Their most common use is not a new build but an extension — a boardroom that has added seats, or a room replacing damaged units without wanting to re-specify the whole system. Because the housing is unchanged across the range, a table with units of different ages still looks uniform, which matters more in an executive room than it might sound. The chairman variant adds the priority function that clears the floor. Sasha Corporation can confirm compatibility with your installed controller and supply, fit, and support the additional positions.",
  },
  {
    id: "cmx-mc-5800e-paperless-conference-management-server",
    slug: "cmx-mc-5800e-paperless-conference-management-server",
    name: "CMX MC-5800E Paperless Conference Management Server",
    model: "MC-5800E",
    brand: CMX,
    systemCategory: "video",
    connection: "wired",
    productTypes: ["processor", "control-unit"],
    price: indicativeRange(485000, 720000),
    availability: "project-order",
    shortDescription:
      "Management server for paperless meetings, distributing agendas and documents to each seat instead of printed packs.",
    images: [
      {
        src: cmxImage("CMX-MC-5800E-Paperless-Conference-Management-Server-300x300.webp"),
        alt: "CMX MC-5800E paperless conference management server",
        primary: true,
      },
    ],
    compatibleProductIds: ["cmx-mc-5802abc-paperless-digital-conference-host"],
    badge: "Paperless System",
    tags: ["CMX", "Paperless Meeting", "Document Server"],
    keyFeatures: [
      "Serves agendas, papers, and voting items to seat terminals over the room network",
      "Removes the printing and collation cycle before every meeting",
      "Central control of which documents are released and when",
      "Built for organisations with confidentiality rules around meeting papers",
    ],
    applications: ["Council Chamber", "Corporate Board", "Regulatory Body"],
    specifications: [
      { key: "Model", value: "MC-5800E" },
      { key: "Series", value: "CMX MC paperless conference range" },
      { key: "Product Type", value: "Paperless conference management server" },
      { key: "System Type", value: "Networked paperless meeting platform" },
      { key: "Connection", value: "Wired network to seat terminals and conference hosts" },
      { key: "Installation", value: "Rack mount in the AV or IT room" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on seat count and integration" },
    ],
    description:
      "The CMX MC-5800E is the server behind a paperless meeting room. Agendas, supporting papers, and voting items are held centrally and released to seat terminals over the room network, which replaces the print-and-collate cycle that precedes most formal meetings. For boards and regulatory bodies the appeal is usually control rather than paper cost: documents can be withheld until the relevant item, and they do not leave the room in someone's folder afterwards. Deployment touches IT as much as AV, so network planning is part of the job. Sasha Corporation can scope the seat count, coordinate with your IT team, and deliver installation, configuration, and support in Bangladesh.",
  },
  {
    id: "cmx-mc-5802abc-paperless-digital-conference-host",
    slug: "cmx-mc-5802abc-paperless-digital-conference-host",
    name: "CMX MC-5802ABC Paperless Digital Conference Host",
    model: "MC-5802ABC",
    brand: CMX,
    systemCategory: "video",
    connection: "wired",
    productTypes: ["control-unit", "processor"],
    price: indicativeRange(395000, 560000),
    availability: "project-order",
    shortDescription:
      "Conference host for paperless rooms, tying the discussion audio and the document platform to one control point.",
    images: [
      {
        src: cmxImage("CMX-MC-5802ABC-Paperless-Digital-Conference-Host-300x300.webp"),
        alt: "CMX MC-5802ABC paperless digital conference host",
        primary: true,
      },
    ],
    compatibleProductIds: ["cmx-mc-5800e-paperless-conference-management-server"],
    badge: "Paperless System",
    tags: ["CMX", "Paperless Meeting", "Conference Host"],
    keyFeatures: [
      "Single control point for discussion audio and paperless seat terminals",
      "Speaker queue and document state stay aligned during an item",
      "Reduces the number of operators needed to run a formal meeting",
      "Integrates with the MC-5800E management server for document handling",
    ],
    applications: ["Council Chamber", "Corporate Board", "Government Meeting Room"],
    specifications: [
      { key: "Model", value: "MC-5802ABC" },
      { key: "Series", value: "CMX MC paperless conference range" },
      { key: "Product Type", value: "Paperless digital conference host" },
      { key: "System Type", value: "Networked paperless meeting platform" },
      { key: "Connection", value: "Wired network to seat terminals and management server" },
      { key: "Installation", value: "Rack mount at the AV position" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on room scale and integration" },
    ],
    description:
      "The CMX MC-5802ABC is the host that runs a paperless conference room from the operator's side. Its value is coordination: the speaker queue and the document currently on the seat terminals stay aligned, so the room is not being driven by two people working from separate consoles. In practice that is what makes a paperless meeting faster than a paper one rather than slower. It works alongside the MC-5800E management server, which handles the document library itself. Sasha Corporation can design the room, define how discussion control and document release should interact for your meeting rules, and provide installation, training, and support in Bangladesh.",
  },
  {
    id: "cmx-mc-5803-paperless-digital-conference-system-host",
    slug: "cmx-mc-5803-paperless-digital-conference-system-host",
    name: "CMX MC-5803 Paperless Digital Conference System Host",
    model: "MC-5803",
    brand: CMX,
    systemCategory: "video",
    connection: "wired",
    productTypes: ["control-unit", "processor"],
    price: indicativeRange(430000, 615000),
    availability: "project-order",
    shortDescription:
      "Higher-capacity paperless conference host for chambers where the seat count and item list are both large.",
    images: [
      {
        src: cmxImage("CMX-MC-5803-Paperless-Digital-Conference-System-Host-300x300.webp"),
        alt: "CMX MC-5803 paperless digital conference system host",
        primary: true,
      },
    ],
    compatibleProductIds: ["cmx-mc-5800e-paperless-conference-management-server"],
    badge: "Paperless System",
    tags: ["CMX", "Paperless Meeting", "Large Chamber"],
    keyFeatures: [
      "Capacity headroom above the MC-5802ABC for larger chambers",
      "Handles long agendas without the operator losing the item sequence",
      "Central management of discussion, documents, and session records",
      "Suited to assemblies where sittings run for a full day",
    ],
    applications: ["Assembly Hall", "Council Chamber", "Large Government Meeting Room"],
    specifications: [
      { key: "Model", value: "MC-5803" },
      { key: "Series", value: "CMX MC paperless conference range" },
      { key: "Product Type", value: "Paperless digital conference system host" },
      { key: "System Type", value: "Networked paperless meeting platform" },
      { key: "Room Scale", value: "Large chambers and assembly halls" },
      { key: "Installation", value: "Rack mount in the AV or control room" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on seat count and session requirements" },
    ],
    description:
      "The CMX MC-5803 is the larger of the CMX paperless conference hosts, intended for chambers where both the seat count and the agenda are substantial. The difference from the smaller host is felt most on long sittings: a full-day agenda with many items puts more strain on the operator than on the hardware, and the MC-5803 is built to keep the item sequence, speaker queue, and document state coherent through that. Assemblies and large council chambers in Bangladesh are the natural fit. Sasha Corporation can scope the installation against your sitting patterns, coordinate the network requirements, and provide commissioning, operator training, and ongoing support.",
  },
  {
    id: "cmx-s800mc-infrared-wireless-conference-controller",
    slug: "cmx-s800mc-infrared-wireless-conference-controller",
    name: "CMX S800MC Infrared Wireless Conference Controller",
    model: "S800MC",
    brand: CMX,
    systemCategory: "audio",
    connection: "wireless",
    productTypes: ["control-unit"],
    price: indicativeRange(198000, 275000),
    availability: "project-order",
    shortDescription:
      "Infrared wireless conference controller for rooms where discussion audio must not pass through walls.",
    images: [
      {
        src: cmxImage("CMX-S800MC-Infrared-Wireless-Conference-Controller-300x300.webp"),
        alt: "CMX S800MC infrared wireless conference controller",
        primary: true,
      },
    ],
    compatibleProductIds: [],
    badge: "Wireless System",
    tags: ["CMX", "Infrared", "Secure Discussion"],
    keyFeatures: [
      "Infrared carrier keeps the discussion audio inside the room's walls",
      "Immune to the Wi-Fi congestion that affects radio-based systems",
      "Suited to closed sessions where radio leakage is a stated concern",
      "Central speak-limit and discussion-mode control from the host",
    ],
    applications: ["Closed Session Room", "Government Meeting Room", "Executive Boardroom"],
    specifications: [
      { key: "Model", value: "S800MC" },
      { key: "Series", value: "CMX infrared wireless conference range" },
      { key: "Product Type", value: "Infrared wireless conference controller" },
      { key: "System Type", value: "Infrared wireless discussion" },
      { key: "Coverage", value: "Line-of-sight within the room; signal does not pass through walls" },
      { key: "Installation", value: "Host unit with room radiators positioned for table coverage" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on room geometry and radiator count" },
    ],
    description:
      "The CMX S800MC uses infrared rather than radio to carry conference audio, and that single choice is the reason to specify it. Infrared does not pass through walls, so a closed session stays acoustically contained in a way no radio system can promise — and it is unaffected by the crowded Wi-Fi environment of a modern office building. The trade-off is line of sight: radiator placement and room geometry decide whether coverage is even, which makes the survey the critical part of the job. Sasha Corporation can carry out that survey, position the radiators correctly, and provide installation, commissioning, and after-sales support in Bangladesh.",
  },
  {
    id: "cmx-uhf-300mc-wireless-conference-master-controller",
    slug: "cmx-uhf-300mc-wireless-conference-master-controller",
    name: "CMX UHF-300MC Wireless Conference Master Controller",
    model: "UHF-300MC",
    brand: CMX,
    systemCategory: "audio",
    connection: "wireless",
    productTypes: ["control-unit"],
    price: indicativeRange(152000, 210000),
    availability: "project-order",
    shortDescription:
      "UHF wireless conference master controller offering longer reach than Wi-Fi in rooms with awkward sightlines.",
    images: [
      {
        src: cmxImage("CMX-UHF-300MC-Wireless-Conference-Master-Controller-300x300.webp"),
        alt: "CMX UHF-300MC wireless conference master controller",
        primary: true,
      },
    ],
    compatibleProductIds: [],
    badge: "Wireless System",
    tags: ["CMX", "UHF Wireless", "Master Controller"],
    keyFeatures: [
      "UHF carrier tolerates pillars and partial obstructions better than infrared",
      "Longer working range than short-band wireless in deep rooms",
      "Central speak-limit management from the master controller",
      "No table cabling, so seating layouts stay flexible",
    ],
    applications: ["Large Meeting Hall", "Hotel Ballroom", "Training Centre"],
    specifications: [
      { key: "Model", value: "UHF-300MC" },
      { key: "Series", value: "CMX UHF wireless conference range" },
      { key: "Product Type", value: "Wireless conference master controller" },
      { key: "System Type", value: "UHF wireless discussion" },
      { key: "Coverage", value: "Room-scale UHF link, tolerant of partial obstruction" },
      { key: "Installation", value: "Rack or shelf mount with antenna placement per site survey" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on unit count and frequency planning" },
    ],
    description:
      "The CMX UHF-300MC is the choice when a room is wireless by necessity but infrared will not cover it. Pillars, deep layouts, and irregular ballroom shapes break the line of sight that infrared depends on; UHF works through those obstructions and reaches further. What it asks in return is frequency planning — the band has to be checked against what else is operating on site, particularly in hotels where wireless microphones are already in use. Sasha Corporation carries out that frequency check as part of the survey, sizes the unit count against the seating, and provides installation, commissioning, and after-sales support in Bangladesh.",
  },
  {
    id: "cmx-us-200mc-digital-conference-system-controller",
    slug: "cmx-us-200mc-digital-conference-system-controller",
    name: "CMX US-200MC Digital Conference System Controller",
    model: "US-200MC",
    brand: CMX,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["control-unit"],
    price: indicativeRange(128000, 178000),
    availability: "project-order",
    shortDescription:
      "Wired digital conference controller for the CMX US platform, sized for standard corporate boardrooms.",
    images: [
      {
        src: cmxImage("CMX-US-200MC-Digital-Conference-System-Controller-300x300.webp"),
        alt: "CMX US-200MC digital conference system controller",
        primary: true,
      },
    ],
    compatibleProductIds: ["cmx-us-201-us-202-chairman-delegate-discussion-units"],
    badge: "Central Unit",
    tags: ["CMX", "US Series", "Digital Controller"],
    keyFeatures: [
      "Wired digital control for US-series chairman and delegate units",
      "Selectable discussion modes including override and request-to-speak",
      "Recorder output for meetings that need a minute-taking feed",
      "Stable, cable-fed operation with no frequency planning required",
    ],
    applications: ["Corporate Boardroom", "Committee Room", "University Meeting Room"],
    specifications: [
      { key: "Model", value: "US-200MC" },
      { key: "Series", value: "CMX US digital conference range" },
      { key: "Product Type", value: "Digital conference system controller" },
      { key: "System Type", value: "Wired digital discussion" },
      { key: "Connection", value: "Wired chain to US-201 and US-202 discussion units" },
      { key: "Installation", value: "Rack or shelf mount at the AV position" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on position count and outputs required" },
    ],
    description:
      "The CMX US-200MC is a wired digital conference controller for rooms that value predictability over flexibility. Everything that makes wireless attractive — no cable, movable tables — also introduces batteries, pairing, and frequency questions. A cable-fed system has none of those, and for a boardroom whose layout does not change, that is usually the better engineering answer. The US-200MC handles discussion modes, speak limits, and a recorder feed for minute-taking. Sasha Corporation can match the controller to your position count, plan the cable routes during fit-out, and provide installation, testing, and after-sales support across Bangladesh.",
  },
  {
    id: "cmx-us-201-us-202-chairman-delegate-discussion-units",
    slug: "cmx-us-201-us-202-chairman-delegate-discussion-units",
    name: "CMX US-201 Chairman & US-202 Delegate Discussion Units",
    model: "US-201 / US-202",
    brand: CMX,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["chairman-unit", "delegate-unit"],
    price: indicativeRange(16500, 24000),
    availability: "project-order",
    shortDescription:
      "Wired chairman and delegate positions for the CMX US platform, with a low-profile housing that suits glass tables.",
    images: [
      {
        src: cmxImage("CMX-US-201-Chairman-US-202-Delegate-Discussion-Units-300x234.webp"),
        alt: "CMX US-201 chairman and US-202 delegate discussion units",
        primary: true,
      },
    ],
    compatibleProductIds: ["cmx-us-200mc-digital-conference-system-controller"],
    badge: "Delegate Unit",
    tags: ["CMX", "US Series", "Table Unit"],
    keyFeatures: [
      "Low-profile housing that stays clear of sightlines across the table",
      "Chairman variant carries the priority key for floor control",
      "Wired connection to the US-200MC controller, no batteries to manage",
      "Speak indicator visible to the chair from across the room",
    ],
    applications: ["Corporate Boardroom", "Committee Room", "Executive Meeting Room"],
    specifications: [
      { key: "Models", value: "US-201 chairman, US-202 delegate" },
      { key: "Series", value: "CMX US digital conference range" },
      { key: "Product Type", value: "Chairman and delegate discussion units" },
      { key: "Chair Function", value: "Priority key to mute active delegate microphones" },
      { key: "Connection", value: "Wired chain to the US-200MC controller" },
      { key: "Installation", value: "Tabletop at chairman and participant positions" },
      { key: "Price Basis", value: "Indicative per-unit range; final quote depends on quantity and split" },
    ],
    description:
      "The CMX US-201 chairman and US-202 delegate units are the table hardware for a US-series room. Their low-profile housing is the practical differentiator: in executive rooms with glass or narrow tables, tall discussion units block sightlines and make video calls awkward, and these sit lower. The chairman version adds the priority key that mutes open delegate microphones. Because they are wired, there are no batteries to charge between meetings and no pairing step when a unit is swapped. Sasha Corporation can work out the chairman-to-delegate ratio, confirm spacing against your table dimensions, and provide supply, installation, and after-sales support in Bangladesh.",
  },
  {
    id: "cmx-ws-100mc-economic-digital-conference-controller",
    slug: "cmx-ws-100mc-economic-digital-conference-controller",
    name: "CMX WS-100MC Economic Digital Conference Controller",
    model: "WS-100MC",
    brand: CMX,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["control-unit"],
    price: indicativeRange(86000, 122000),
    availability: "project-order",
    shortDescription:
      "Budget-conscious digital conference controller for small rooms and first-time installations.",
    images: [
      {
        src: cmxImage("CMX-WS-100MC-Economic-Digital-Conference-Controller-300x300.png"),
        alt: "CMX WS-100MC economic digital conference controller",
        primary: true,
      },
    ],
    compatibleProductIds: ["cmx-ws-257-ws-258-chairman-delegate-units"],
    badge: "Central Unit",
    tags: ["CMX", "WS Series", "Entry Controller"],
    keyFeatures: [
      "Lowest-cost entry into the CMX WS discussion platform",
      "Core discussion control without the interfaces larger rooms need",
      "Sized honestly for small meeting rooms rather than oversold",
      "Upgrade path to larger WS controllers using the same table units",
    ],
    applications: ["Small Meeting Room", "Departmental Office", "Training Room"],
    specifications: [
      { key: "Model", value: "WS-100MC" },
      { key: "Series", value: "CMX WS digital conference range" },
      { key: "Product Type", value: "Entry digital conference controller" },
      { key: "System Type", value: "Wired digital discussion" },
      { key: "Room Scale", value: "Small meeting rooms" },
      { key: "Installation", value: "Shelf or rack mount with wired chain to table units" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on position count" },
    ],
    description:
      "The CMX WS-100MC is the entry point to the WS discussion platform, and it is worth being clear about what that means: it delivers the core discussion control a small room needs and leaves out the interfaces a large one would want. For a departmental meeting room or a first conference installation, that is the right trade. The useful part is the upgrade path — the WS table units carry over to the larger WS controllers, so growing the room later does not mean replacing everything. Sasha Corporation will tell you honestly whether your room fits this controller or needs the next one up, and can supply, install, and support either.",
  },
  {
    id: "cmx-ws-200mc-digital-conference-system-controller",
    slug: "cmx-ws-200mc-digital-conference-system-controller",
    name: "CMX WS-200MC Digital Conference System Controller",
    model: "WS-200MC",
    brand: CMX,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["control-unit"],
    price: indicativeRange(135000, 188000),
    availability: "project-order",
    shortDescription:
      "Main WS-series digital conference controller, the usual specification for a full corporate boardroom.",
    images: [
      {
        src: cmxImage("CMX-WS-200MC-Digital-Conference-System-Controller-300x300.webp"),
        alt: "CMX WS-200MC digital conference system controller",
        primary: true,
      },
    ],
    compatibleProductIds: ["cmx-ws-200rt-digital-conference-expansion-host", "cmx-ws-259-ws-260-chairman-delegate-units"],
    badge: "Central Unit",
    tags: ["CMX", "WS Series", "Digital Controller"],
    keyFeatures: [
      "Full discussion mode set including override and request-to-speak queueing",
      "Recorder and external amplifier outputs for minutes and hall reinforcement",
      "Expandable with the WS-200RT host when positions exceed one controller",
      "Works with the full WS range of chairman and delegate units",
    ],
    applications: ["Corporate Boardroom", "Council Chamber", "University Meeting Hall"],
    specifications: [
      { key: "Model", value: "WS-200MC" },
      { key: "Series", value: "CMX WS digital conference range" },
      { key: "Product Type", value: "Digital conference system controller" },
      { key: "System Type", value: "Wired digital discussion" },
      { key: "Expansion", value: "Supports the WS-200RT expansion host for larger position counts" },
      { key: "Installation", value: "Rack mount at the AV position" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on position count and expansion" },
    ],
    description:
      "The CMX WS-200MC is the controller most WS-series boardrooms end up specifying. It carries the full discussion mode set, the recorder and amplifier outputs a working meeting room needs, and — importantly — a defined expansion route through the WS-200RT host when the table grows past what one controller drives. That last point is what separates it from the entry WS-100MC: the room can expand without the controller becoming the thing that has to be replaced. It pairs with any of the WS chairman and delegate units. Sasha Corporation can size the system against your seating, plan for expansion, and provide installation, commissioning, and support in Bangladesh.",
  },
  {
    id: "cmx-ws-200rt-digital-conference-expansion-host",
    slug: "cmx-ws-200rt-digital-conference-expansion-host",
    name: "CMX WS-200RT Digital Conference Expansion Host",
    model: "WS-200RT",
    brand: CMX,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["control-unit", "accessory"],
    price: indicativeRange(72000, 105000),
    availability: "project-order",
    shortDescription:
      "Expansion host that extends a WS-200MC installation beyond the position count one controller can drive.",
    images: [
      {
        src: cmxImage("CMX-WS-200RT-Digital-Conference-Expansion-Host-300x300.webp"),
        alt: "CMX WS-200RT digital conference expansion host",
        primary: true,
      },
    ],
    compatibleProductIds: ["cmx-ws-200mc-digital-conference-system-controller"],
    badge: "Expansion Unit",
    tags: ["CMX", "WS Series", "System Expansion"],
    keyFeatures: [
      "Adds capacity to an existing WS-200MC room without replacing the controller",
      "Extends the discussion chain for long tables and tiered chambers",
      "Keeps one operator interface across the expanded system",
      "Protects the original investment when seating grows",
    ],
    applications: ["Council Chamber", "Large Boardroom", "Assembly Hall"],
    specifications: [
      { key: "Model", value: "WS-200RT" },
      { key: "Series", value: "CMX WS digital conference range" },
      { key: "Product Type", value: "Conference system expansion host" },
      { key: "Function", value: "Extends position capacity of a WS-200MC installation" },
      { key: "Connection", value: "Wired link to the main controller and onward discussion chain" },
      { key: "Installation", value: "Rack mount alongside the main controller" },
      { key: "Price Basis", value: "Indicative project range; final quote depends on added position count" },
    ],
    description:
      "The CMX WS-200RT exists for a specific situation: a WS-200MC room that has run out of positions. Rather than replacing a working controller, the expansion host extends the discussion chain and keeps the whole system under one operator interface. For council chambers and tiered halls that add seats over time, this is what makes the original specification hold its value. It is worth planning the expansion route at first fit-out even if the extra host is not purchased then, because cable provision is far cheaper during construction than after. Sasha Corporation can plan that headroom, supply the expansion when it is needed, and support the combined system.",
  },
  {
    id: "cmx-ws-257-ws-258-chairman-delegate-units",
    slug: "cmx-ws-257-ws-258-chairman-delegate-units",
    name: "CMX WS-257 Chairman & WS-258 Delegate Units",
    model: "WS-257 / WS-258",
    brand: CMX,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["chairman-unit", "delegate-unit"],
    price: indicativeRange(15500, 22500),
    availability: "project-order",
    shortDescription:
      "Compact wired chairman and delegate units for WS-series rooms where table space is tight.",
    images: [
      {
        src: cmxImage("CMX-WS-257-Chairman-WS-258-Delegate-Units-300x300.webp"),
        alt: "CMX WS-257 chairman and WS-258 delegate conference units",
        primary: true,
      },
    ],
    compatibleProductIds: ["cmx-ws-100mc-economic-digital-conference-controller"],
    badge: "Delegate Unit",
    tags: ["CMX", "WS Series", "Compact Unit"],
    keyFeatures: [
      "Small footprint that leaves working space for papers and laptops",
      "Chairman priority key for clearing the floor",
      "Wired chain, so no charging routine between meetings",
      "Economical option for filling a table with many positions",
    ],
    applications: ["Training Room", "Departmental Boardroom", "Committee Room"],
    specifications: [
      { key: "Models", value: "WS-257 chairman, WS-258 delegate" },
      { key: "Series", value: "CMX WS digital conference range" },
      { key: "Product Type", value: "Compact chairman and delegate discussion units" },
      { key: "Footprint", value: "Reduced tabletop footprint for tight seating pitches" },
      { key: "Connection", value: "Wired chain to a CMX WS controller" },
      { key: "Installation", value: "Tabletop at each seating position" },
      { key: "Price Basis", value: "Indicative per-unit range; final quote depends on quantity" },
    ],
    description:
      "The CMX WS-257 chairman and WS-258 delegate units address a problem that only appears once a table is full: discussion units competing with papers, water glasses, and laptops for the same surface. Their reduced footprint gives each participant usable working space, which matters most in training rooms and committee rooms where seating pitch is tight and the meeting runs long. They are also the economical way to populate a table with many positions. Sasha Corporation can check the unit spacing against your actual table dimensions before quoting — a step worth taking, because seating plans on paper often assume more room than exists.",
  },
  {
    id: "cmx-ws-259-ws-260-chairman-delegate-units",
    slug: "cmx-ws-259-ws-260-chairman-delegate-units",
    name: "CMX WS-259 Chairman & WS-260 Delegate Units",
    model: "WS-259 / WS-260",
    brand: CMX,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["chairman-unit", "delegate-unit"],
    price: indicativeRange(18500, 27000),
    availability: "project-order",
    shortDescription:
      "Standard WS-series chairman and delegate pair, the middle specification between the compact and premium units.",
    images: [
      {
        src: cmxImage("CMX-WS-259-Chairman-WS-260-Delegate-Units-300x300.webp"),
        alt: "CMX WS-259 chairman and WS-260 delegate conference units",
        primary: true,
      },
    ],
    compatibleProductIds: ["cmx-ws-200mc-digital-conference-system-controller"],
    badge: "Chairman Unit",
    tags: ["CMX", "WS Series", "Standard Unit"],
    keyFeatures: [
      "Balanced size and build for everyday boardroom use",
      "Chairman priority function with a clearly separated key",
      "Speak indicator ring readable from across a large table",
      "Direct pairing with the WS-200MC controller",
    ],
    applications: ["Corporate Boardroom", "Government Meeting Room", "University Meeting Hall"],
    specifications: [
      { key: "Models", value: "WS-259 chairman, WS-260 delegate" },
      { key: "Series", value: "CMX WS digital conference range" },
      { key: "Product Type", value: "Chairman and delegate discussion units" },
      { key: "Chair Function", value: "Dedicated priority key separated from the speak key" },
      { key: "Connection", value: "Wired chain to the WS-200MC controller" },
      { key: "Installation", value: "Tabletop at chairman and participant positions" },
      { key: "Price Basis", value: "Indicative per-unit range; final quote depends on quantity and split" },
    ],
    description:
      "The CMX WS-259 and WS-260 are the standard table units in the WS range — larger and more solid than the compact WS-257/258, without the premium finish of the top models. For most corporate and government boardrooms this is the sensible specification. Two details earn their place in daily use: the priority key is physically separated from the speak key, so a chair does not clear the floor by accident, and the indicator ring is bright enough to read from the far end of a long table. Sasha Corporation can supply matched quantities, plan the table layout, and handle installation, testing, and after-sales support in Bangladesh.",
  },
  {
    id: "cmx-ws-261-ws-262-chairman-delegate-units",
    slug: "cmx-ws-261-ws-262-chairman-delegate-units",
    name: "CMX WS-261 Chairman & WS-262 Delegate Units",
    model: "WS-261 / WS-262",
    brand: CMX,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["chairman-unit", "delegate-unit"],
    price: indicativeRange(22500, 33000),
    availability: "project-order",
    shortDescription:
      "Upper WS-series chairman and delegate units for executive rooms where the table hardware is on show.",
    images: [
      {
        src: cmxImage("CMX-WS-261-Chairman-WS-262-Delegate-Units-300x300.webp"),
        alt: "CMX WS-261 chairman and WS-262 delegate conference units",
        primary: true,
      },
    ],
    compatibleProductIds: ["cmx-ws-200mc-digital-conference-system-controller"],
    badge: "Chairman Unit",
    tags: ["CMX", "WS Series", "Executive Finish"],
    keyFeatures: [
      "Higher-grade finish for rooms where the table is photographed",
      "Chairman priority function with the same operation as the standard units",
      "Heavier base that resists being pushed out of alignment",
      "Fully interchangeable with other WS units on the same controller",
    ],
    applications: ["Executive Boardroom", "Ministerial Meeting Room", "Corporate Head Office"],
    specifications: [
      { key: "Models", value: "WS-261 chairman, WS-262 delegate" },
      { key: "Series", value: "CMX WS digital conference range" },
      { key: "Product Type", value: "Executive chairman and delegate discussion units" },
      { key: "Finish", value: "Upper-tier housing and base weighting" },
      { key: "Connection", value: "Wired chain to a CMX WS controller" },
      { key: "Installation", value: "Tabletop at chairman and participant positions" },
      { key: "Price Basis", value: "Indicative per-unit range; final quote depends on quantity and split" },
    ],
    description:
      "The CMX WS-261 and WS-262 are the executive tier of the WS table range. Functionally they do what the standard units do; what you pay for is finish and weight. In ministerial rooms and corporate head offices the conference table appears in photographs and on broadcast feeds, and hardware that looks substantial matters there in a way it does not in a training room. The heavier base also keeps units aligned through a day of people leaning on the table. They remain fully interchangeable with other WS units on the same controller. Sasha Corporation can mix tiers across a room — executive units at the head, standard along the sides — and supply, install, and support the result.",
  },
  {
    id: "cmx-ws-273m-ws-274m-chairman-delegate-units",
    slug: "cmx-ws-273m-ws-274m-chairman-delegate-units",
    name: "CMX WS-273M Chairman & WS-274M Delegate Units",
    model: "WS-273M / WS-274M",
    brand: CMX,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["chairman-unit", "delegate-unit"],
    price: indicativeRange(24500, 35500),
    availability: "project-order",
    shortDescription:
      "WS-series chairman and delegate units with an extended microphone stem for deeper tables.",
    images: [
      {
        src: cmxImage("CMX-WS-273M-Chairman-WS-274M-Delegate-Units-300x300.webp"),
        alt: "CMX WS-273M chairman and WS-274M delegate conference units",
        primary: true,
      },
    ],
    compatibleProductIds: ["cmx-ws-200mc-digital-conference-system-controller"],
    badge: "Chairman Unit",
    tags: ["CMX", "WS Series", "Long Microphone"],
    keyFeatures: [
      "Extended gooseneck reaches the speaker across a deep table edge",
      "Better pickup distance for participants who sit back from the table",
      "Chairman priority function matching the rest of the WS range",
      "Same controller compatibility as the standard WS units",
    ],
    applications: ["Council Chamber", "Wide Boardroom", "Assembly Hall"],
    specifications: [
      { key: "Models", value: "WS-273M chairman, WS-274M delegate" },
      { key: "Series", value: "CMX WS digital conference range" },
      { key: "Product Type", value: "Long-stem chairman and delegate discussion units" },
      { key: "Microphone", value: "Extended gooseneck for greater reach from the unit base" },
      { key: "Connection", value: "Wired chain to a CMX WS controller" },
      { key: "Installation", value: "Tabletop, suited to deep or tiered table profiles" },
      { key: "Price Basis", value: "Indicative per-unit range; final quote depends on quantity and split" },
    ],
    description:
      "The CMX WS-273M and WS-274M carry a longer microphone stem than the rest of the WS table range, and the reason is geometry rather than preference. On deep tables and tiered chamber desks the unit sits further from the speaker than the designer of a standard gooseneck assumed, and pickup suffers — participants lean forward, or are simply not heard. The extended stem closes that gap. They share controller compatibility and chairman priority behaviour with the other WS units, so a room can use them only where the geometry demands it. Sasha Corporation can identify which positions need the longer stem during the site survey and supply, install, and support accordingly.",
  },
];
