import type { ConferenceProduct } from "./catalog";

const SPON_IMAGE_BASE = "/images/conference_system_products/spon_products";
const requestPrice = { type: "request", currency: "BDT", displayLabel: "Request Price" } as const;

export const newSponConferenceProducts: ConferenceProduct[] = [
  {
    id: "spon-lcs-8004htp-lcs-8008htp-lcs-8016htp",
    slug: "spon-lcs-8004htp-lcs-8008htp-lcs-8016htp",
    name: "LCS-8004HTP/LCS-8008HTP/LCS-8016HTP",
    model: "LCS-8004HTP / LCS-8008HTP / LCS-8016HTP",
    brand: { name: "SPON", slug: "spon" },
    systemCategory: "video",
    connection: "wired",
    systemFamily: "LCS-800 HTP",
    productTypes: ["processor"],
    price: requestPrice,
    availability: "contact",
    shortDescription: "Seamless HDMI video matrix family with multiple control options and 4, 8, or 16-input configurations.",
    description: "The LCS-8004HTP/LCS-8008HTP/LCS-8016HTP is a seamless HDMI video matrix family for conference rooms and professional AV systems. Three configurations support different source counts, while multiple control options help integrators manage video routing for room-specific requirements. The LCS-8004HTP configuration accepts four HDMI inputs and supports resolutions up to 4K at 30Hz.",
    keyFeatures: ["Seamless HDMI video matrix", "Multiple control options", "Three configurations available", "Up to 4K at 30Hz on the LCS-8004HTP configuration"],
    specifications: [
      { key: "Product Type", value: "Video matrix" },
      { key: "Models", value: "LCS-8004HTP, LCS-8008HTP, LCS-8016HTP" },
      { key: "Power Supply", value: "DC 5V, 1A (LCS-8004HTP)" },
      { key: "Input Signal", value: "4 x HDMI (LCS-8004HTP)" },
      { key: "Input Connectors", value: "Type A 19-pin female" },
      { key: "Input Resolution", value: "Up to 4K at 30Hz; RGB 4:4:4, YCbCr 4:4:4, YCbCr 4:2:2" },
      { key: "HDMI Standard", value: "HDMI 1.4" },
      { key: "HDMI Embedded Audio", value: "PCM" },
      { key: "Analog Audio", value: "4 x 3.5 mm audio interfaces" },
      { key: "Control Port", value: "2 x RS-232, 1 x Ethernet, 1 x RJ45" },
      { key: "Product Dimensions", value: "482.8 (W) x 236 (D) x 44 (H) mm" },
      { key: "Product Weight", value: "2 kg" },
    ],
    applications: ["Conference Room", "Boardroom AV", "Training Facility"],
    compatibleProductIds: [],
    images: [{ src: `${SPON_IMAGE_BASE}/LCS-800XHTP.webp`, alt: "SPON LCS-8004HTP, LCS-8008HTP and LCS-8016HTP seamless HDMI video matrix models", primary: true }],
    badge: "Video Matrix",
    tags: ["SPON", "Video Matrix", "HDMI", "4K"],
  },
  {
    id: "spon-lcs-2883a",
    slug: "spon-lcs-2883a-omnidirectional-microphone",
    name: "LCS-2883A",
    model: "LCS-2883A",
    brand: { name: "SPON", slug: "spon" },
    systemCategory: "audio",
    connection: "hybrid",
    productTypes: ["speakerphone", "microphone"],
    price: requestPrice,
    availability: "contact",
    shortDescription: "Omnidirectional conference microphone with 360-degree pickup, full-duplex echo cancellation, Bluetooth, and USB connectivity.",
    description: "The LCS-2883A is an omnidirectional conference microphone for meeting rooms and collaborative spaces. Its four-metre, 360-degree pickup coverage supports group discussion, while full-duplex echo cancellation and noise suppression help maintain clear two-way communication. Bluetooth and USB modes provide flexible connection options, and two RJ9 interfaces support expansion microphones.",
    keyFeatures: ["360-degree pickup coverage", "Full-duplex echo cancellation", "Bluetooth and USB dual mode", "Noise suppression"],
    specifications: [
      { key: "Product Type", value: "Omnidirectional microphone" },
      { key: "Power Supply", value: "DIN6 connector and USB socket" },
      { key: "USB Interface", value: "1 x USB 3.0 Type-B" },
      { key: "RJ9 Ports", value: "2 x RJ9 expansion microphone interfaces" },
      { key: "Analog Audio", value: "1 x 3.5 mm audio interface" },
      { key: "Microphone Frequency Response", value: "100 Hz–22 kHz" },
      { key: "Speaker Frequency Response", value: "100 Hz–22 kHz" },
      { key: "Microphone Pickup Range", value: "4 m, 360-degree omnidirectional" },
      { key: "Maximum Speaker Volume", value: "90 dB" },
      { key: "Acoustic Echo Cancellation", value: ">65 dB" },
      { key: "Echo Cancellation Length", value: ">500 ms" },
    ],
    applications: ["Meeting Room", "Huddle Room", "Video Conference"],
    compatibleProductIds: [],
    images: [{ src: `${SPON_IMAGE_BASE}/LCS-2883A.webp`, alt: "SPON LCS-2883A omnidirectional conference microphone", primary: true }],
    badge: "Speakerphone",
    tags: ["SPON", "Omnidirectional Microphone", "Bluetooth", "USB"],
  },
  {
    id: "spon-lcs-2870d",
    slug: "spon-lcs-2870d-inverted-camera-bracket",
    name: "LCS-2870D",
    model: "LCS-2870D",
    brand: { name: "SPON", slug: "spon" },
    systemCategory: "video",
    productTypes: ["accessory"],
    price: requestPrice,
    availability: "contact",
    shortDescription: "Inverted camera bracket designed for neat, space-saving installation of the LCS-2876-4K camera.",
    description: "The LCS-2870D is an inverted camera bracket for the LCS-2876-4K conference camera. Its installation-focused design supports a neat, space-saving camera position in meeting rooms and professional video conferencing environments.",
    keyFeatures: ["Inverted camera bracket", "Easy installation design", "Space-saving and neat setup", "Suitable for LCS-2876-4K"],
    specifications: [{ key: "Product Type", value: "Inverted camera bracket" }, { key: "Compatibility", value: "LCS-2876-4K" }, { key: "Installation", value: "Inverted camera mounting" }],
    applications: ["Conference Room", "Video Conference", "Meeting Room"],
    compatibleProductIds: [],
    images: [{ src: `${SPON_IMAGE_BASE}/LCS-2870D.webp`, alt: "SPON LCS-2870D inverted conference camera bracket", primary: true }],
    badge: "Camera Bracket",
    tags: ["SPON", "Camera Bracket", "LCS-2876-4K"],
  },
  {
    id: "spon-lcs-2871d",
    slug: "spon-lcs-2871d-inverted-camera-bracket",
    name: "LCS-2871D",
    model: "LCS-2871D",
    brand: { name: "SPON", slug: "spon" },
    systemCategory: "video",
    productTypes: ["accessory"],
    price: requestPrice,
    availability: "contact",
    shortDescription: "Inverted camera bracket designed for neat, space-saving installation of the LCS-2871-20 camera.",
    description: "The LCS-2871D is an inverted camera bracket for the LCS-2871-20 conference camera. Its straightforward mounting design helps create a tidy, space-efficient camera setup for conference rooms and professional video collaboration spaces.",
    keyFeatures: ["Inverted camera bracket", "Easy installation design", "Space-saving and neat setup", "Suitable for LCS-2871-20"],
    specifications: [{ key: "Product Type", value: "Inverted camera bracket" }, { key: "Compatibility", value: "LCS-2871-20" }, { key: "Installation", value: "Inverted camera mounting" }],
    applications: ["Conference Room", "Video Conference", "Meeting Room"],
    compatibleProductIds: ["spon-lcs-2871-20"],
    images: [{ src: `${SPON_IMAGE_BASE}/LCS-2871D.webp`, alt: "SPON LCS-2871D inverted conference camera bracket", primary: true }],
    badge: "Camera Bracket",
    tags: ["SPON", "Camera Bracket", "LCS-2871-20"],
  },
  {
    id: "spon-lcs-2871-20",
    slug: "spon-lcs-2871-20-hd-conference-camera",
    name: "LCS-2871-20",
    model: "LCS-2871-20",
    brand: { name: "SPON", slug: "spon" },
    systemCategory: "video",
    productTypes: ["camera"],
    price: requestPrice,
    availability: "contact",
    shortDescription: "Full HD conference camera with a 5.5–110 mm lens, 10x digital zoom, and quiet pan-tilt operation.",
    description: "The LCS-2871-20 is a Full HD conference camera designed for meeting rooms, training facilities, and larger video conferencing spaces. Its 2.07-megapixel CMOS sensor, 5.5–110 mm lens, quiet pan-tilt mechanism, and multiple video output interfaces support detailed room coverage and flexible AV integration. Automatic and manual image controls allow the camera to be adjusted for different lighting and installation conditions.",
    keyFeatures: ["Full HD image", "Super-silent pan-tilt", "Audio input interfaces", "Multiple video output interfaces"],
    specifications: [
      { key: "Product Type", value: "HD conference camera" }, { key: "Power Supply", value: "DC 12V, 1A" }, { key: "Power Consumption", value: "<12 W" },
      { key: "Image Sensor", value: "1/2.8-inch high-quality CMOS sensor" }, { key: "Effective Pixels", value: "2.07 million, 16:9 aspect ratio" },
      { key: "Lens", value: "f=5.5–110 mm" }, { key: "Field of View", value: "3.45° narrow to 60.04° wide" }, { key: "Aperture", value: "F1.8–F2.9" },
      { key: "Digital Zoom", value: "10x" }, { key: "Minimum Illumination", value: "0.5 lux (F1.8, AGC on)" },
      { key: "Digital Noise Reduction", value: "2D and 3D digital noise reduction" }, { key: "White Balance", value: "Auto, manual, one-push, 3000K–7000K presets" },
      { key: "Focus", value: "Auto, manual, one-push focus" }, { key: "Electronic Shutter", value: "Auto or manual" }, { key: "Backlight Compensation", value: "On or off" },
      { key: "Dynamic Range", value: "Off or dynamic-level adjustment" }, { key: "Video Adjustment", value: "Brightness, contrast, sharpness, image flip, black-and-white mode, gamma, electronic zoom, DCI, and lens-distortion correction" },
      { key: "Signal-to-Noise Ratio", value: ">55 dB" }, { key: "Product Dimensions", value: "258 x 172 x 169 mm" }, { key: "Product Weight", value: "1.46 kg" },
      { key: "Packed Dimensions", value: "350 x 275 x 255 mm" }, { key: "Gross Weight", value: "3.2 kg" },
    ],
    applications: ["Boardroom", "Training Room", "Conference Hall"],
    compatibleProductIds: ["spon-lcs-2871d"],
    images: [{ src: `${SPON_IMAGE_BASE}/2af217e477.webp`, alt: "SPON LCS-2871-20 HD conference camera", primary: true }],
    badge: "Conference Camera",
    tags: ["SPON", "Conference Camera", "Full HD", "10x Digital Zoom"],
  },
  {
    id: "spon-lcs-5203l",
    slug: "spon-lcs-5203l-digital-conference-central-unit",
    name: "LCS-5203L",
    model: "LCS-5203L",
    brand: { name: "SPON", slug: "spon" },
    systemCategory: "audio",
    productTypes: ["control-unit"],
    price: requestPrice,
    availability: "contact",
    warranty: "2 years",
    shortDescription: "Digital conference central unit with a 4.3-inch color interface, lossless 48 kHz audio, ring networking, remote access, sign-in, and voting.",
    description: "The LCS-5203L is a rack-mounted digital conference central unit designed to manage professional meeting and discussion systems. Its 4.3-inch color interface supports system operation, while ring-network flexibility helps maintain a structured conference topology. Lossless 48 kHz audio, wireless remote access, sign-in, and voting functions support boardrooms, council chambers, and formal conference environments.",
    keyFeatures: ["4.3-inch color UI screen", "Lossless 48 kHz audio", "Ring-network flexibility", "Wireless remote access", "Sign-in and voting"],
    specifications: [
      { key: "Product Type", value: "Digital conference central unit" },
      { key: "Power Supply", value: "AC 100-240V, 50-60Hz" },
      { key: "Standby Power Consumption", value: "<=10 W" },
      { key: "Audio Codec", value: "MP3, PCM, ADPCM" },
      { key: "Signal-to-Noise Ratio", value: ">83 dB" },
      { key: "Audio Sampling and Bitrate", value: "8 kHz-44.1 kHz, 16-bit; 8 kbps-320 kbps" },
      { key: "Mounting Method", value: "Rack-mounted" },
      { key: "Installation Environment", value: "Dry indoor locations only" },
      { key: "Frequency Response", value: "40 Hz-18 kHz" },
      { key: "Operating Temperature", value: "0°C to +45°C (-4°F to 113°F)" },
      { key: "Operating Humidity", value: "<=90% RH non-condensing" },
      { key: "Body Material", value: "Surface-treated steel plate" },
      { key: "Housing Material", value: "Surface-treated steel plate" },
      { key: "Product Warranty", value: "2 years" },
      { key: "Gross Weight", value: "4.4 kg" },
      { key: "Packed Dimensions", value: "550 x 380 x 155 mm" },
      { key: "Product Dimensions", value: "483 x 229.5 x 89 mm" },
    ],
    applications: ["Boardroom", "Council Chamber", "Conference Hall"],
    compatibleProductIds: [],
    images: [{ src: `${SPON_IMAGE_BASE}/LCS-5203L.webp`, alt: "SPON LCS-5203L digital conference central unit", primary: true }],
    badge: "Central Unit",
    tags: ["SPON", "Digital Conference", "Central Unit", "Voting"],
  },
  {
    id: "spon-lcm-6013dvw-l",
    slug: "spon-lcm-6013dvw-l-wireless-microphone-delegate-unit",
    name: "LCM-6013DVW-L",
    model: "LCM-6013DVW-L",
    brand: { name: "SPON", slug: "spon" },
    systemCategory: "audio",
    connection: "wireless",
    productTypes: ["delegate-unit"],
    price: requestPrice,
    availability: "contact",
    shortDescription: "Wireless microphone delegate unit with long battery life, real-time speaker information, video tracking, and secure wireless encryption.",
    description: "The LCM-6013DVW-L is a wireless microphone delegate unit for flexible conference and meeting-room layouts. It displays real-time speaker information on a capacitive touch screen and supports video tracking, secure wireless encryption, and multiple wireless frequencies. A 4000 mAh lithium battery provides up to six hours of continuous talk time for scheduled meetings and formal discussions.",
    keyFeatures: ["Long battery life", "Real-time speaker information", "Video tracking capability", "Secure wireless encryption", "Multiple wireless frequencies"],
    specifications: [
      { key: "Product Type", value: "Wireless microphone delegate unit" },
      { key: "Power Consumption", value: "3 W" },
      { key: "Lithium Battery", value: "4000 mAh" },
      { key: "Signal-to-Noise Ratio and Frequency Response", value: ">=83 dB; 40 Hz-18 kHz" },
      { key: "Operating Time", value: "6 hours continuous talk; approximately 8 hours screen-on standby" },
      { key: "Screen", value: "4-inch capacitive touch screen" },
      { key: "Screen Resolution", value: "480 x 480 RGB" },
      { key: "Headphone Output", value: "3.5 mm stereo jack" },
      { key: "Connectivity", value: "Wi-Fi wireless connection" },
      { key: "Microphone Polar Pattern", value: "Supercardioid" },
      { key: "Microphone Sensitivity", value: "-38 dB, 12.6 mV/Pa (0 dB = 1 V/Pa at 1 kHz)" },
      { key: "Microphone Maximum SPL", value: "130 dB SPL (1% THD at 1 kHz)" },
      { key: "Operating Temperature and Humidity", value: "0°C to +45°C, <=90% RH non-condensing" },
      { key: "Microphone Base Dimensions", value: "168 x 103 x 289 mm" },
    ],
    applications: ["Boardroom", "Council Meeting", "Conference Room"],
    compatibleProductIds: [],
    images: [{ src: `${SPON_IMAGE_BASE}/LCM-6013DVW-L.webp`, alt: "SPON LCM-6013DVW-L wireless microphone delegate unit", primary: true }],
    badge: "Wireless Delegate Unit",
    tags: ["SPON", "Wireless Delegate Unit", "Video Tracking", "Touch Screen"],
  },
];
