import type { ConferenceProduct } from "./catalog";

const BOSCH_IMAGE_BASE = "/images/conference_system_products/bosch_products";
const BOSCH = { name: "Bosch", slug: "bosch" } as const;
const requestPrice = { type: "request", currency: "BDT", displayLabel: "Request Price" } as const;

export const newBoschConferenceProducts: ConferenceProduct[] = [
  {
    id: "bosch-ccsd-cl-discussion-chairman-unit",
    slug: "bosch-ccsd-cl-discussion-chairman-unit",
    name: "Bosch CCSD-CL Discussion Chairman Unit",
    model: "CCSD-CL",
    brand: BOSCH,
    systemCategory: "audio",
    productTypes: ["chairman-unit"],
    price: requestPrice,
    availability: "contact",
    shortDescription: "Discussion chairman unit with a color-coded microphone status indicator, built-in loudspeaker, and tabletop installation.",
    description: "The Bosch CCSD-CL Discussion Chairman Unit gives the chairperson a clear speaking position in organized meetings and discussions. Its color-coded LED indicates active, queued, next-to-speak, and possible-to-speak states. A built-in loudspeaker, headphone connection, and tabletop form factor support boardrooms, council meetings, and formal conference spaces.",
    keyFeatures: ["Color-coded microphone status indication", "Built-in loudspeaker", "Chairman discussion control", "Portable or fixed tabletop mounting"],
    specifications: [
      { key: "Product Type", value: "Discussion chairman unit" },
      { key: "Frequency Response", value: "200 Hz-12.5 kHz" },
      { key: "Headphone Load Impedance", value: ">32 ohms and <1 kohm" },
      { key: "Loudspeaker Nominal Output", value: "72 dB SPL" },
      { key: "Device Dimensions", value: "64 x 203 x 146 mm without microphone" },
      { key: "Height with Horizontal Microphone", value: "130 mm" },
      { key: "Microphone Length", value: "CCSD-DS: 310 mm; CCSD-DL: 480 mm" },
      { key: "Weight", value: "Approximately 1 kg" },
      { key: "Mounting", value: "Tabletop, portable or fixed" },
      { key: "Top Material", value: "ABS+PC plastic" },
      { key: "Base Material", value: "ZnAl4 metal" },
      { key: "Color", value: "Traffic black top and pearl light grey base" },
      { key: "Operating Temperature", value: "0°C to +35°C" },
      { key: "Storage Temperature", value: "-40°C to +70°C" },
      { key: "Relative Humidity", value: "15%-90%" },
      { key: "Air Pressure", value: "600-1100 hPa" },
    ],
    applications: ["Boardroom", "Council Chamber", "Conference Room"],
    compatibleProductIds: [],
    images: [{ src: `${BOSCH_IMAGE_BASE}/Bosch CCSD-CL Discussion Chairman Unit.webp`, alt: "Bosch CCSD-CL Discussion Chairman Unit", primary: true }],
    badge: "Chairman Unit",
    tags: ["Bosch", "CCSD-CL", "Chairman Unit", "Discussion System"],
  },
  {
    id: "bosch-lbb-4116-05-dcn-extension-cable-5m",
    slug: "bosch-lbb-4116-05-dcn-extension-cable-5m",
    name: "Bosch LBB 4116/05 DCN Extension Cable 5m",
    model: "LBB 4116/05",
    brand: BOSCH,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["accessory"],
    price: requestPrice,
    availability: "contact",
    shortDescription: "Five-metre grey DCN extension cable with molded six-pin DIN male and female network connectors.",
    description: "The Bosch LBB 4116/05 DCN Extension Cable 5m extends a compatible DCN conference network between system devices. It uses molded six-pin DIN male and female connectors with copper conductors and a grey PVC jacket for professional indoor conference installations.",
    keyFeatures: ["5 m DCN extension cable", "Molded six-pin DIN connectors", "Copper conductor", "Grey PVC jacket"],
    specifications: [
      { key: "Product Type", value: "DCN extension cable" }, { key: "Cable Type", value: "DIN" }, { key: "Cable Length", value: "5 m (16.40 ft)" },
      { key: "Connector 1", value: "6-pin DIN male network connector" }, { key: "Connector 2", value: "6-pin DIN female network connector" },
      { key: "Conductor", value: "Copper" }, { key: "Material", value: "PVC jacket" }, { key: "Color", value: "Grey" },
    ],
    applications: ["Conference Network Extension", "Boardroom Installation", "DCN System Cabling"],
    compatibleProductIds: [],
    images: [{ src: `${BOSCH_IMAGE_BASE}/bosch-lbb-4116-05-dcn-extension-cable-5m-in-bd.webp`, alt: "Bosch LBB 4116/05 DCN Extension Cable 5m", primary: true }],
    badge: "Extension Cable",
    tags: ["Bosch", "LBB 4116/05", "DCN Cable", "5m"],
  },
  {
    id: "bosch-lbb-4116-10-dcn-extension-cable-10m",
    slug: "bosch-lbb-4116-10-dcn-extension-cable-10m",
    name: "Bosch LBB 4116/10 DCN Extension Cable – 10m",
    model: "LBB 4116/10",
    brand: BOSCH,
    systemCategory: "audio",
    connection: "wired",
    productTypes: ["accessory"],
    price: requestPrice,
    availability: "contact",
    shortDescription: "Ten-metre DCN audio extension cable with DIN male and female connectors for compatible conference devices.",
    description: "The Bosch LBB 4116/10 DCN Extension Cable – 10m provides additional cable length for compatible Bosch DCN conference audio devices. The grey cable uses DIN male and female audio connectors and a PVC jacket for fixed indoor conference-system cabling.",
    keyFeatures: ["10 m extension length", "DIN male and female audio connectors", "Designed for compatible DCN audio devices", "Grey PVC jacket"],
    specifications: [
      { key: "Product Type", value: "Audio extension cable" }, { key: "Product Series", value: "LBB 4116" }, { key: "Cable Type", value: "DIN" },
      { key: "Cable Length", value: "10 m (32.81 ft)" }, { key: "Connector 1", value: "6-pin DIN male audio connector" },
      { key: "Connector 2", value: "6-pin DIN female audio connector" }, { key: "Device Supported", value: "Audio device" },
      { key: "Material", value: "PVC jacket" }, { key: "Color", value: "Grey" }, { key: "Weight", value: "1.6 lb" },
    ],
    applications: ["Conference Network Extension", "Meeting Room Cabling", "DCN Audio System"],
    compatibleProductIds: [],
    images: [{ src: `${BOSCH_IMAGE_BASE}/bosch-lbb-411610-dcn-extension-cable-10m.webp`, alt: "Bosch LBB 4116/10 DCN Extension Cable 10m", primary: true }],
    badge: "Extension Cable",
    tags: ["Bosch", "LBB 4116/10", "DCN Cable", "10m"],
  },
  {
    id: "bosch-dcnm-wd-dicentis-wireless-discussion-device",
    slug: "bosch-dcnm-wd-dicentis-wireless-discussion-device",
    name: "Bosch DCNM-WD DICENTIS Wireless Discussion Device",
    model: "DCNM-WD",
    brand: BOSCH,
    systemCategory: "audio",
    connection: "wireless",
    systemFamily: "DICENTIS Wireless",
    productTypes: ["delegate-unit", "chairman-unit"],
    price: requestPrice,
    availability: "contact",
    shortDescription: "Secure dual-band Wi-Fi discussion device configurable for single-use, dual-use, or chairperson operation.",
    description: "The Bosch DCNM-WD DICENTIS Wireless Discussion Device enables participants to speak, request to speak, and listen during meetings. Through the DCNM-WAP web interface it can be configured for single-use, dual-use, or chairperson operation. Dual-band Wi-Fi, WPA2 security, automatic channel switching, and built-in feedback suppression support secure and intelligible wireless discussion.",
    keyFeatures: ["Configurable single-use, dual-use, or chairperson operation", "2.4 GHz and 5 GHz Wi-Fi", "WPA2-secured wireless connectivity", "Built-in acoustic feedback suppression"],
    specifications: [
      { key: "Product Type", value: "Wireless discussion device" }, { key: "Wireless Standard", value: "IEEE 802.11n" },
      { key: "Frequency Range", value: "2.4 GHz and 5 GHz license-free bands" }, { key: "Security", value: "WPA2 encryption" },
      { key: "Configuration", value: "Single-use, dual-use, or chairperson" }, { key: "Microphone Compatibility", value: "DCNM-HDMIC, DCNM-MICS, or DCNM-MICL" },
      { key: "Headphone Connections", value: "Two independently controlled connections" }, { key: "Access Point", value: "Connects to DCNM-WAP" },
    ],
    applications: ["Wireless Boardroom", "Council Meeting", "Conference Room"],
    compatibleProductIds: ["bosch-dcnm-hdmic-dicentis-wireless-microphone", "bosch-dcnm-wliion-battery-pack-for-dcnm-wd"],
    images: [{ src: `${BOSCH_IMAGE_BASE}/bosch-dcnm-wd-dicentis-wireless-discussion-device-min.webp`, alt: "Bosch DCNM-WD DICENTIS Wireless Discussion Device", primary: true }],
    badge: "Wireless Discussion Device",
    tags: ["Bosch", "DICENTIS", "DCNM-WD", "Wireless Discussion"],
  },
  {
    id: "bosch-dcnm-wch05-dicentis-charger-for-5-batteries",
    slug: "bosch-dcnm-wch05-dicentis-charger-for-5-batteries",
    name: "Bosch DCNM-WCH05 DICENTIS Charger for 5 Batteries",
    model: "DCNM-WCH05",
    brand: BOSCH,
    systemCategory: "audio",
    systemFamily: "DICENTIS Wireless",
    productTypes: ["charger", "accessory"],
    price: requestPrice,
    availability: "contact",
    shortDescription: "DICENTIS charger for simultaneously charging up to five individual wireless discussion-device battery packs.",
    description: "The Bosch DCNM-WCH05 DICENTIS Charger for 5 Batteries supports simultaneous charging of five individual DICENTIS battery packs. Battery packs recharge in less than three hours, while the auto-ranging and loop-through mains supply support practical charging arrangements for wireless conference systems.",
    keyFeatures: ["Simultaneous charging", "Five individual battery-pack positions", "Recharge time under three hours", "Auto-ranging and loop-through mains supply"],
    specifications: [{ key: "Product Type", value: "Battery charger" }, { key: "Charging Capacity", value: "5 battery packs" }, { key: "Charging Time", value: "Less than 3 hours" }, { key: "Power Supply", value: "Auto-ranging with loop mains connection" }],
    applications: ["Wireless Conference System", "Battery Charging Station", "Equipment Room"],
    compatibleProductIds: ["bosch-dcnm-wliion-battery-pack-for-dcnm-wd"],
    images: [{ src: `${BOSCH_IMAGE_BASE}/bosch-dcnm-wch05-dicentis-charger-for-5-batteries-min.webp`, alt: "Bosch DCNM-WCH05 DICENTIS charger for five batteries", primary: true }],
    badge: "Battery Charger",
    tags: ["Bosch", "DICENTIS", "DCNM-WCH05", "Battery Charger"],
  },
  {
    id: "bosch-dcnm-hdmic-dicentis-wireless-microphone",
    slug: "bosch-dcnm-hdmic-dicentis-wireless-microphone",
    name: "Bosch DCNM-HDMIC Dicentis Wireless Microphone",
    model: "DCNM-HDMIC",
    brand: BOSCH,
    systemCategory: "audio",
    systemFamily: "DICENTIS Wireless",
    productTypes: ["microphone", "accessory"],
    price: requestPrice,
    availability: "contact",
    shortDescription: "Highly directive, ultra-low-noise pluggable microphone designed for DICENTIS wireless discussion devices.",
    description: "The Bosch DCNM-HDMIC Dicentis Wireless Microphone is a pluggable microphone for compatible DICENTIS wireless discussion desks. Its highly directive response supports focused speech pickup, while low susceptibility to mobile-phone interference and ultra-low noise help maintain clear conference audio with freedom of movement.",
    keyFeatures: ["Highly directive response", "Low susceptibility to mobile phones", "Ultra-low noise", "Designed for DICENTIS wireless desks"],
    specifications: [{ key: "Product Type", value: "Pluggable wireless discussion microphone" }, { key: "Directivity", value: "Highly directive" }, { key: "Compatibility", value: "DICENTIS wireless discussion desk" }],
    applications: ["Wireless Discussion Desk", "Boardroom", "Conference Room"],
    compatibleProductIds: ["bosch-dcnm-wd-dicentis-wireless-discussion-device"],
    images: [{ src: `${BOSCH_IMAGE_BASE}/bosch-dcnm-hdmic-dicentis-wireless-microphone-min.webp`, alt: "Bosch DCNM-HDMIC DICENTIS wireless microphone", primary: true }],
    badge: "Wireless Microphone",
    tags: ["Bosch", "DICENTIS", "DCNM-HDMIC", "Microphone"],
  },
  {
    id: "bosch-ccse-cura-central-control-unit-recorder-amplifier",
    slug: "bosch-ccse-cura-central-control-unit-recorder-amplifier",
    name: "Bosch CCSE-CURA Central Control unit with Recorder and Amplifier",
    model: "CCSE-CURA-IN",
    brand: BOSCH,
    systemCategory: "audio",
    connection: "wired",
    systemFamily: "CCS700 Ultro",
    productTypes: ["control-unit", "amplifier"],
    price: requestPrice,
    availability: "contact",
    shortDescription: "CCS700 central controller with recording, delegate and chairman microphone control, and an integrated 30 W rated amplifier.",
    description: "The Bosch CCSE-CURA Central Control unit with Recorder and Amplifier is the control and power center of a CCS700 Ultro Discussion System. It supplies connected chairman and delegate units, manages their microphones, interfaces with external audio equipment, and includes an amplifier for meeting and small conference venues.",
    keyFeatures: ["Central control for CCS700 discussion units", "Integrated recording and amplifier", "External audio interfaces", "Plug-and-play conference operation"],
    specifications: [
      { key: "Product Type", value: "Controller unit with recorder and amplifier" }, { key: "Mains Voltage", value: "220-230 VAC, 50 Hz" },
      { key: "DC Supply to Units", value: "24 V DC +/-1 V" }, { key: "Mic Input Sensitivity", value: "1 mV (+1/-3 dB)" },
      { key: "Aux Input Sensitivity", value: "100 mV (+1/-3 dB)" }, { key: "Input Frequency Response", value: "200 Hz-12 kHz (+/-3 dB)" },
      { key: "Aux Input Impedance", value: "100 kohm, single-ended" }, { key: "Maximum Output Power", value: "45 W" },
      { key: "Rated Output Power", value: "30 W" }, { key: "Amplifier Frequency Response", value: "80 Hz-18 kHz" },
      { key: "Loudspeaker Output", value: "100 V, 8 ohm or 4 ohm via Phoenix connector" }, { key: "Distortion", value: "<1% at rated power, 1 kHz" },
      { key: "Operating Temperature", value: "+5°C to +45°C" }, { key: "Storage Temperature", value: "-20°C to +70°C" },
      { key: "Product Dimensions", value: "88 x 433 x 252 mm" }, { key: "Weight", value: "6 kg" }, { key: "Color", value: "Charcoal and grey" },
    ],
    applications: ["Meeting Room", "Small Conference Venue", "Discussion System"],
    compatibleProductIds: [],
    images: [{ src: `${BOSCH_IMAGE_BASE}/bosch-ccse-cura-control-unit-with-recorder-and-amplifier.webp`, alt: "Bosch CCSE-CURA central control unit with recorder and amplifier", primary: true }],
    badge: "Central Control Unit",
    tags: ["Bosch", "CCSE-CURA", "CCS700 Ultro", "Controller"],
  },
  {
    id: "bosch-dcnm-wliion-battery-pack-for-dcnm-wd",
    slug: "bosch-dcnm-wliion-battery-pack-for-dcnm-wd",
    name: "Bosch DCNM-WLIION Battery Pack for DCNM-WD",
    model: "DCNM-WLIION",
    brand: BOSCH,
    systemCategory: "audio",
    systemFamily: "DICENTIS Wireless",
    productTypes: ["accessory"],
    price: requestPrice,
    availability: "contact",
    shortDescription: "Removable 12,800 mAh lithium-ion battery pack providing up to 24 hours of typical DCNM-WD operation.",
    description: "The Bosch DCNM-WLIION Battery Pack for DCNM-WD is a removable rechargeable lithium-ion power pack for DICENTIS wireless discussion devices. It fully recharges in less than three hours and provides up to 24 hours of typical use in the standard wireless device or 20 hours in the extended device. Integrated charge-current control and a push-to-test button support practical battery management.",
    keyFeatures: ["Up to 24 hours of typical use", "Full recharge in under three hours", "12,800 mAh lithium-ion capacity", "Push-to-test remaining-capacity indication"],
    specifications: [
      { key: "Product Type", value: "Rechargeable lithium-ion battery pack" }, { key: "Nominal Output Voltage", value: "7.5 V DC" },
      { key: "Capacity", value: "12,800 mAh" }, { key: "Typical Operating Time", value: "24 hours with DCNM-WD; 20 hours with DCNM-WDE" },
      { key: "Charging Time", value: "Less than 3 hours" }, { key: "Product Dimensions", value: "99.9 x 136.5 x 22 mm" },
      { key: "Weight", value: "1,774 g" }, { key: "Color", value: "Charcoal" }, { key: "Operating Temperature", value: "+5°C to +45°C" },
      { key: "Advised Storage Temperature", value: "-5°C to +35°C" }, { key: "Relative Humidity", value: ">5% and <75%" },
    ],
    applications: ["Wireless Conference System", "DICENTIS Discussion Device", "Battery Rotation"],
    compatibleProductIds: ["bosch-dcnm-wd-dicentis-wireless-discussion-device", "bosch-dcnm-wch05-dicentis-charger-for-5-batteries"],
    images: [{ src: `${BOSCH_IMAGE_BASE}/Bosch DCNM-WLIION Battery Pack for DCNM-WD.webp`, alt: "Bosch DCNM-WLIION battery pack for DCNM-WD", primary: true }],
    badge: "Battery Pack",
    tags: ["Bosch", "DICENTIS", "DCNM-WLIION", "Battery Pack"],
  },
];
