import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import type { ReactNode } from "react";
import Breadcrumbs from "@/components/common/Breadcrumbs";
import { homeBreadcrumb } from "@/lib/breadcrumbs";
import { absoluteUrl, socialImageUrl } from "@/lib/seo";
import { siteConfig } from "@/lib/site";
import { getPaSystemBySlug, getPaSystemCardPriceLabel } from "./catalog";
import { PA_HERO, paPageItems, paPriceRows, paCategory, applications, systemTypes, speakerGuide, signalSteps, processSteps, supportItems, faqs } from "./landing-data";
import PaIcon, { type PaIconName } from "./PaIcon";
import PaSystemProducts from "./PaSystemProducts";
import styles from "./pa-landing.module.css";

const title = "PA System Price in Bangladesh 2026";
const description = "Explore PA speakers, amplifiers, microphones and paging systems in Bangladesh. Compare catalog prices and plan your site with BOQ, installation and support.";
export const metadata: Metadata = {
  title, description, alternates: { canonical: "/pa-system/" },
  openGraph: { title, description, type: "website", url: absoluteUrl("/pa-system/"), images: [{ url: socialImageUrl(PA_HERO), width: 2290, height: 687, alt: "PA sound equipment and an outdoor stage setup" }] },
  twitter: { card: "summary_large_image", title, description, images: [socialImageUrl(PA_HERO)] },
};
function Badge({ icon }: { icon: PaIconName }) { return <span className={styles.iconBadge}><PaIcon name={icon} /></span>; }
function Heading({ eyebrow, title, text, link }: { eyebrow?: string; title: string; text: string; link?: { href: string; label: string } }) {
  return <div className={styles.heading}><div>{eyebrow && <p className={styles.eyebrow}>{eyebrow}</p>}<h2>{title}</h2><p className={styles.description}>{text}</p></div>{link && <Link className={styles.textLink} href={link.href}>{link.label}<PaIcon name="arrow" /></Link>}</div>;
}
function Section({ id, tone, children }: { id: string; tone?: "soft" | "blue"; children: ReactNode }) {
  return <section id={id} className={`${styles.section} ${tone ? styles[tone] : ""}`}><div className={styles.container}>{children}</div></section>;
}
export default function PaSystemPage() {
  const wa = `https://api.whatsapp.com/send/?phone=${siteConfig.whatsapp.replace(/\D/g, "")}&text=${encodeURIComponent("Hello, I would like a PA system recommendation and BOQ. I can share my site layout, audio requirements and zones.")}`;
  const schema = { "@context": "https://schema.org", "@type": "CollectionPage", "@id": absoluteUrl("/pa-system/"), url: absoluteUrl("/pa-system/"), name: title, description,
    mainEntity: { "@type": "ItemList", numberOfItems: paPageItems.length, itemListElement: paPageItems.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.title, url: absoluteUrl(`/pa-system/${item.slug}/`) })) } };
  return <div className={styles.page} data-pa-landing>
    <Breadcrumbs items={[homeBreadcrumb(), { href: "/pa-system/", label: "PA System", current: true }]} className="sr-only" showBackLink={false} />
    <section className={styles.hero} aria-labelledby="pa-title">
      <div className={styles.heroVisual}><Image src={PA_HERO} alt="PA speakers, audio mixer, microphones and rack equipment beside an outdoor stage" fill priority sizes="100vw" /></div>
      <div className={`${styles.container} ${styles.heroInner}`}><div className={styles.heroCopy}>
        <p className={styles.eyebrow}>PUBLIC ADDRESS & PROFESSIONAL AUDIO</p><h1 id="pa-title">PA System Price<br />in Bangladesh 2026</h1><p className={styles.heroAccent}>Clear Sound. Thoughtfully Planned.</p>
        <p className={styles.heroDescription}>Speakers, amplifiers, microphones and paging solutions for mosques, schools, offices and commercial spaces—with project-based planning, installation and support.</p>
        <div className={styles.actions}><Link href="/contact/" className={styles.primary}><PaIcon name="plan" />Get a PA System BOQ</Link><a href="#pa-products" className={styles.outline}>Explore Products<PaIcon name="arrow" /></a></div>
        <div className={styles.heroTags}>{["Speech & BGM", "Zone-wise Paging", "Setup & Support"].map(text => <span key={text}><PaIcon name="check" />{text}</span>)}</div>
      </div></div>
    </section>
    <div className={styles.trustBand}><div className={`${styles.container} ${styles.trustGrid}`}><div><strong>Complete PA System Planning</strong><span>Equipment · BOQ · Installation · Support</span></div>{[{ icon: "plan", title: "Site-Led Design", text: "Layout, coverage & zones" }, { icon: "settings", title: "System Integration", text: "Sources, controls & speakers" }, { icon: "headset", title: "Practical Support", text: "Handover & after-sales" }].map(item => <div key={item.title}><Badge icon={item.icon as PaIconName} /><div><strong>{item.title}</strong><span>{item.text}</span></div></div>)}</div></div>
    <nav className={styles.sectionNav} aria-label="On this PA system page"><div className={styles.container}>{[["pa-products", "Products"], ["pa-applications", "By Application"], ["pa-system-guide", "System Guide"], ["pa-price-list", "Price List"], ["pa-installation", "Installation"], ["pa-faq", "FAQs"]].map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</div></nav>

    <Section id="pa-products" tone="soft"><div className={styles.catalogPanel}><Heading title="Browse PA Products" text="Explore PA speakers, amplifiers, microphones, and complete sound systems in one product explorer." /><PaSystemProducts items={paPageItems} /></div></Section>
    <Section id="pa-applications"><Heading eyebrow="PLANNED AROUND YOUR SITE" title="A PA Solution for Every Environment" text="Start with how your space is used, then match the speakers, controls and installation plan." link={{ href: "/contact/", label: "Discuss Your Site" }} /><div className={styles.applicationGrid}>{applications.map(item => <article className={styles.applicationCard} key={item.title}><Badge icon={item.icon} /><h3>{item.title}</h3><p>{item.text}</p><div className={styles.componentHint}>{item.components}</div></article>)}</div></Section>
    <Section id="pa-system-guide" tone="blue"><Heading eyebrow="UNDERSTAND YOUR OPTIONS" title="Choose a System That Fits Your Workflow" text="A public address system brings audio sources, amplification and speakers together. The right architecture depends on your site." /><div className={styles.systemGrid}>{systemTypes.map((item, index) => <article className={styles.systemCard} key={item.title}><div className={styles.cardTop}><span className={styles.pill}>{item.label}</span><span className={styles.stepNumber}>0{index + 1}</span></div><h3>{item.title}</h3><p>{item.text}</p><ul className={styles.checks}>{item.points.map(point => <li key={point}><PaIcon name="check" /><span>{point}</span></li>)}</ul></article>)}</div><div className={styles.signalPanel}><h3>How Your Audio Reaches the Room</h3><ol className={styles.signalGrid}>{signalSteps.map((item, index) => <li key={item.title}><Badge icon={item.icon} /><div><strong>{item.title}</strong><p>{item.text}</p></div>{index < 3 && <span className={styles.signalArrow}><PaIcon name="arrow" /></span>}</li>)}</ol></div></Section>
    <Section id="pa-speakers"><Heading eyebrow="SPEAKER SELECTION GUIDE" title="The Right Speaker, in the Right Place" text="Use these as planning starting points; final coverage and suitability depend on the exact model and installation." /><div className={styles.speakerGrid}>{speakerGuide.map(item => { const product = getPaSystemBySlug(item.slug)!; return <article className={styles.speakerCard} key={item.slug}><Link href={`/pa-system/${item.slug}/`} prefetch={false} aria-label={`View ${product.title}`} className={styles.speakerImage}><Image className={/column_speaker/.test(product.kind) ? styles.containImage : undefined} src={product.image} alt={product.title} fill sizes="(max-width: 599px) 45vw, 22vw" /></Link><div><h3>{item.title}</h3><strong>{item.text}</strong><p>{item.note}</p><Link href={`/pa-system/${item.slug}/`} prefetch={false} className={styles.textLink}>View Example<PaIcon name="arrow" /></Link></div></article>; })}</div></Section>
    <Section id="pa-price-list" tone="soft"><Heading eyebrow="PLAN YOUR BUDGET" title="PA System Price List in Bangladesh" text="Existing catalog prices for selected products. A complete system needs a site-specific equipment and installation quotation." /><div className={styles.priceLayout}><div className={styles.tableWrap}><div className={styles.priceTableIntro}><div><Badge icon="speaker" /><div><strong>Selected PA Equipment</strong><span>Catalog price reference in BDT</span></div></div><span>{paPriceRows.length} items</span></div><table><caption className="sr-only">Indicative PA equipment prices in BDT</caption><thead><tr><th scope="col">PA equipment</th><th scope="col">Catalog price</th></tr></thead><tbody>{paPriceRows.map(item => <tr key={item.slug}><td><Link href={`/pa-system/${item.slug}/`} prefetch={false} className={styles.priceProductLink}><span>{item.title}</span><small>{paCategory(item)}</small></Link></td><td><span className={styles.priceValue}>{getPaSystemCardPriceLabel(item) ?? "On request"}</span></td></tr>)}</tbody></table></div><aside className={styles.quotePanel}><div className={styles.quoteLabel}><Badge icon="plan" /><span>PROJECT-SPECIFIC PLANNING</span></div><h3>What Shapes Your Quotation?</h3><ul className={styles.checks}>{["Coverage area and listening conditions", "Speaker quantity and amplifier capacity", "Paging zones and audio sources", "Cable runs, mounting and rack work", "Testing, training and support scope"].map(text => <li key={text}><PaIcon name="check" /><span>{text}</span></li>)}</ul><Link href="/contact/" className={styles.primary}>Request a Project BOQ<PaIcon name="arrow" /></Link><p>Share a floor plan, room dimensions or a list of requirements to get started.</p></aside></div></Section>
    <section className={styles.support} aria-labelledby="pa-support-title"><Image src={PA_HERO} alt="" fill sizes="100vw" className={styles.backdrop} /><div className={styles.container}><p className={styles.eyebrow}>SUPPORT BEYOND THE EQUIPMENT</p><h2 id="pa-support-title">From Your First Plan to Everyday Operation</h2><p className={styles.description}>A practical approach to specification, installation and ongoing system care.</p><div className={styles.supportGrid}>{supportItems.map(item => <article key={item.title}><Badge icon={item.icon} /><div><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div></div></section>
    <Section id="pa-installation"><Heading eyebrow="SIMPLE, STRUCTURED DELIVERY" title="How We Plan & Install Your PA System" text="Agree the scope first, then move through equipment selection, installation and handover." /><ol className={styles.processGrid}>{processSteps.map((item, index) => <li key={item.title}><span className={styles.processNumber}>0{index + 1}</span><h3>{item.title}</h3><p>{item.text}</p></li>)}</ol><div className={styles.planningNote}><PaIcon name="shield" /><p><strong>Planning emergency announcements?</strong> Ordinary PA equipment should not be assumed suitable for a life-safety system. Confirm the approved design, compatibility and project requirements with qualified specialists.</p></div></Section>
    <Section id="pa-faq" tone="blue"><Heading eyebrow="BEFORE YOU CHOOSE" title="Frequently Asked Questions About PA Systems" text="Practical answers about pricing, equipment, system design and support." /><div className={styles.faqGrid}>{faqs.map((item, index) => <details key={item.q}><summary><span>{String(index + 1).padStart(2, "0")}</span><h3>{item.q}</h3><span className={styles.faqToggle} aria-hidden="true" /></summary><p>{item.a}</p></details>)}</div><div className={styles.related}><span>Explore related solutions</span><Link href="/conference-system/">Conference Systems<PaIcon name="arrow" /></Link><Link href="/interactive-flat-panel/">Interactive Flat Panels<PaIcon name="arrow" /></Link><Link href="/led-display/">LED Displays<PaIcon name="arrow" /></Link></div><details className={styles.directory}><summary>All PA catalog product links ({paPageItems.length})</summary><ul>{paPageItems.map(item => <li key={item.slug}><Link href={`/pa-system/${item.slug}/`} prefetch={false}>{item.title}</Link></li>)}</ul></details></Section>
    <section className={styles.ctaSection} aria-labelledby="pa-cta-title"><div className={styles.container}><div className={styles.cta}><Image src={PA_HERO} alt="" fill sizes="90vw" className={styles.backdrop} /><div><p className={styles.eyebrow}>LET’S PLAN YOUR SOUND SYSTEM</p><h2 id="pa-cta-title">Clearer Sound Starts with the Right Plan.</h2><p>Share your site, zones and audio needs. We’ll help define the equipment and project scope.</p></div><div className={styles.ctaActionPanel}><div className={styles.actions}><Link href="/contact/" className={styles.primary}>Request a PA Quote<PaIcon name="arrow" /></Link><a href={wa} target="_blank" rel="noopener noreferrer" className={styles.whatsapp}><PaIcon name="chat" />Chat on WhatsApp</a></div><div className={styles.ctaBenefits}><span><PaIcon name="plan" />BOQ Support</span><span><PaIcon name="settings" />System Planning</span><span><PaIcon name="headset" />Technical Guidance</span></div></div></div></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
  </div>;
}
